### ISSUE TITLE
[BUG] Error handler (FE): PHP Warning

### ISSUE THREAD

**Issue by medarob** [in2code-de/femanager#101]
Hi,

I'm currently using TYPO3 7.6.31 & PHP 7.1.22 and I get the following error message in the backend whenever someone opens the page with the login form.

Core: Error handler (FE): PHP Warning: Declaration of In2code\MyExtFemanager\Controller\NewController::createAction(In2code\MyExtFemanager\Domain\Model\User $user) should be compatible with In2code\Femanager\Controller\NewController::createAction(In2code\Femanager\Domain\Model\User $user) in /var/www/typo3/typo3conf/ext/my_ext_femanager/Classes/Controller/NewController.php line 37

I found a possible fix here: https://stackoverflow.com/questions/45563671/how-to-extend-femanager-controller-under-php-7/45564378

Maybe you can integrate this into the femanager directly and hopefully this will solve the problem...?

Thank you

**Comment by sbusemann** [comment]
is this problem still valid for the current version of TYPO3 and femanager?

**Comment by medarob** [comment]
We updated to TYPO3 8.7.26 and now the problem seems to be gone. I see no warning. :)
