### ISSUE TITLE
Resend user confirmation email from backend module

### ISSUE THREAD

**Issue by lexflex64** [in2code-de/femanager#104]
Hi, first of all thanks for this plugin it's awesome.

Y try to use the resend user confirmation email action from backend module.
But in the mail received the link is like this

http://exemple.fr/typo3/index.php?M=web_FemanagerM1&moduleToken=7fb8524ead62a9d6c9116eadd7e68c38ab0a61d8&id=221&tx_femanager_pi1%5Buser%5D=11&tx_femanager_pi1%5Bhash%5D=7ef1e897ac5b16cb&tx_femanager_pi1%5Bstatus%5D=userConfirmation&tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New

Of course it's dont work for feuser in FE, i try to modify the f:link.action in template CreatUserConfirmation  whit a pageUid but in BE context extbase use buildBackendUri fonction and

/**
     * Builds the URI, backend flavour
     * The resulting URI is relative and starts with "index.php".
     * The settings pageUid, pageType, noCache, useCacheHash & linkAccessRestrictedPages
     * will be ignored in the backend.
     *
     * @return string The URI
     */

I can use the view Resend confirmation user in FE but i want to do in Backend because like this the admin can create or  hide and resend confirmation all in one place.

Any clue?

Thanks

TYPO3 8.7.19
femanager 4.2.2

**Comment by sbusemann** [comment]
Works in TYPO3 12 - Version 8 - I will not investigate this for older versions anymore.
