### ISSUE TITLE
Wrong version and update information

### ISSUE THREAD

**Issue by kludikovsky** [in2code-de/femanager#105]
Just a minor issue.

The documentation says that any version >3 is for T3 version 8.7 only.

I have 7.6.23 and get in TER an update information to version 3.0.0

Would I do this update I most probably would break my installation.

![image](https://user-images.githubusercontent.com/6077916/47646020-ea645a00-db72-11e8-919b-1d3be1e855ff.png)

**Comment by georgringer** [comment]
Extension Manager does not hard respect the version restriction. As TYPO3 7 is end of life anyway, you  must update to 8 to be safe regarding security. it does not help much having secure extensions but unsafe core ^^.

@einpraegsam I would propose to close it

**Comment by einpraegsam** [comment]
Thx
