### ISSUE TITLE
Processing of settings

### ISSUE THREAD

**Issue by kludikovsky** [in2code-de/femanager#106]
__Related to 2.6.x__

Can anyone here explain to me, why basically two identical lines have different effects.

__Background__

I used the femanager to allow users register for newsletters.

When I developed this in early 2017 this worked. Now I have got feedback that there are errors.

Checked and found that it makes a difference when I use the bracket format vs. single line format for the settings.

This system is on PHP 5.6

The result
![image](https://user-images.githubusercontent.com/6077916/47707187-7afe7100-dc2b-11e8-9506-610a9fb329ab.png)

The Settings

![image](https://user-images.githubusercontent.com/6077916/47706838-843b0e00-dc2a-11e8-8c4d-8eaf02b15dde.png)

The resulting settings

![image](https://user-images.githubusercontent.com/6077916/47706787-666da900-dc2a-11e8-931e-a4719c9a3129.png)

**Comment by georgringer** [comment]
I have never seen the syntax with a dot as first char as in your screenshot in line 10-15. that is for sure wrong syntax

@einpraegsam I would propose closing this issue

**Comment by einpraegsam** [comment]
Thx
