### ISSUE TITLE
[DOC] Suggestion: Rename Subgroup to Basegroup in the settings

### ISSUE THREAD

**Issue by kludikovsky** [in2code-de/femanager#113]
In the FE-usergroup there is a defintion of **subgroup** a group belongs to.

This term implies somewhat the group itself is split into those subgroups and itself is a supergroup of the subgroups. Which actually is not the case.

In reality the 'subgroup' is a group this group inherits their rights.

I would therefor suggest to rename the item from '**subgroup**' to '**basegroup**' which would better describe it function, as the group is based on the basegroups rights.

**Comment by sbusemann** [comment]
The definition is set by TYPO3 itself. So I can not change it. But you can open an issue at https://forge.typo3.org/projects/typo3cms-core/issues
