### ISSUE TITLE
No flashmessage after user confirmation

### ISSUE THREAD

**Issue by mediaessenz** [in2code-de/femanager#114]
I'm currently not sure if this is a bug in the new TYPO3 Version 8.7.21 or femanager.

Anyway, I have an installation with femanager who uses just the user confirmation to activate a profile.

Normally, after the user clicks on the confirmation link inside the generated mail, he should finally get redirected to the createStatusAction, which itself outputs a headline and a flashmessage "profile created".

Unfortunately there is no flashmessage anymore. 

After digging into the code, I found the place where this message is added (AbstractController, Line 246):
```
$this->addFlashMessage(LocalizationUtility::translate('create'));
```
Right after this, there is a redirect to the action stored inside the $redirectByActionName variable.
That's "createStatus" in my case.
I have no clue why, but after the redirect to the "createStatusAction" of the New-Controller, the flashmessage set shortly before is gone.
If I add a $this->addFlashMessage to the createStatusAction, I get a flashmessage in the frontend.

So it seems, flashmessages defined before a redirect get lost.

If I change the redirect `$this->redirect($redirectByActionName);` in the AbstractController to `$this->forward($redirectByActionName);`, the flashmessage reaches the frontend.

**Comment by klodeckl** [comment]
Same here.
According to this tutorial, the user also should get logged in automatically, but there is no autologin: https://jweiland.net/video-anleitungen/typo3/interessante-typo3-extensions/femanager.html
Also a bug?

**Comment by eliashaeussler** [comment]
Hi guys,
any progress on this? We encounter the same issue on TYPO3 8.7.24 and femanager 4.2.2. Switching from `redirect()` to `forward()` as @mediaessenz described solved the issue for us as well.

**Comment by sbusemann** [comment]
is changed for V 6 Release

**Comment by sbusemann** [comment]
needs to be reverted, as this has side effects for persistence. SendPost and StoreInDB services do not work anymore.

**Comment by icehawk-de** [comment]
Issue still present.
Sometimes the flashmessage appears, but most of the time not.

**Comment by markijan** [comment]
February 2024, femanager v. 7.2.3, TYPO3 11.x - bug still exists...
In my case (user confirmation required, FlashMessage createRequestWaitingForUserConfirm) changing the line
https://github.com/in2code-de/femanager/blob/19191f5cee4084683fd9bcdb10e861242f5cab8a/Classes/Controller/NewController.php#L333
to 
$this->forward('createStatus');
fixed FlashMessage issue after profile creation.

**Comment by pixeldesu** [comment]
I tried reproducing this in Femanager 8 now, but the flash message appears after confirming with a user confirmation. 

n fact, even multiple do in case of the Femanager testing setup, both the "You're logged in now" and "Profile successfully created" message appear.

**Comment by sbusemann** [comment]
I will close this issue. We will reopen it, if we have clear steps to reproduce it
