### ISSUE TITLE
destination of the terms and condition link via typoscript

### ISSUE THREAD

**Issue by leofuehringer** [in2code-de/femanager#117]
Is it possible to define the target of the terms and condition link via typoscript? Or is it only via flexform possible?

Configuration/FlexForms/FlexFormPi1.xml
> (<f:link.page pageUid="{**settings.misc.termsUrl**}"><f:translate key="tx_femanager_domain_model_user.termslinktext" /></f:link.page>)

**Comment by sbusemann** [comment]
Yes, no other way atm.
