### ISSUE TITLE
Validation of "passwort repeat" field fails in 4.2.3

### ISSUE THREAD

**Issue by a-tze** [in2code-de/femanager#119]
We have an "update profile" content element that allows FE users to change their passwords, but nothing else.
After upgrading to 4.2.3 no password change can be submitted. It gives a "validation failed" on the second password input field. Downgrading to 4.2.2 resolves the issue.

I can see that 2 validation AJAX requests are sent, one per input field. The first is successful, the second one gets the error returned. FWIW: the second request has an empty value on `tx_femanager_pi1[field]` in the POST data.

**Comment by djangones** [comment]
I can confirm that problem also for the user account creation. The password_repeat field allways gets a "Field could not be validated" witch makes it impossible to rgister with a password...

**Comment by spoonerWeb** [comment]
JS code in Validation.js needs to be this:

```
function getFieldName(element) {
	var name = '';
	var nameParts = element.prop('name').split('[');
	if (nameParts[2] !== undefined) {
		name = nameParts[2].replace(']', '');
	} else {
		name = nameParts[1].replace(']', '');
	}
	return name;
}
```

**Comment by sbusemann** [comment]
this is fixed in dev branch. Thx for reporting and providing a solution.

**Comment by a-tze** [comment]
May I ask if you already plan a 4.2.4 release?

**Comment by sbusemann** [comment]
there is a plan

**Comment by sbusemann** [comment]
soon®
