### ISSUE TITLE
Error on all required fields

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#124]
Hi,
after Ext. Update on 4.2.4 on all fields with required is the Error MSg:

> Error
> Field could not be validated 

i need chance settings after the update?

**Comment by felixmaechtle** [comment]
I do have the same error: Everytime the focus leaves an input element it shows an error. It does not matter if the field is valid or not.

**Comment by Capaman** [comment]
I have the same issue. How can this be solved? Many thanks

**Comment by einpraegsam** [comment]
Thx for the note. We should make this breaking but necessary change more popular. @sbusemann Any idea where to place such a note?

**Comment by georgringer** [comment]
what about releasing it as 5x and use the changelog?

**Comment by einpraegsam** [comment]
Are talking about what have been done better on the security release or do you wrote about what's the next step?

**Comment by georgringer** [comment]
as next step

**Comment by ingeniumdesign** [comment]
hi, i check all Templates and Settings. But the validationEdit Part dont works:

```
# Validation for second Step (Edit)
				validationEdit {
					# Enable clientside Formvalidation (JavaScript)
					_enable.client = 1

					# Enable serverside Formvalidation (PHP)
					_enable.server = 1

					password {
						required = 1
						min = 6
						#mustInclude = number,letter,special
					}
					password_repeat {
						required = 1
						sameAs = password
					}
					terms {
						required = 1
					}
				}
```

all the time is a "valide Error"

**Comment by sbusemann** [comment]
@ingeniumdesign please compare your html templates and JSvalidation with one of the extension. See: https://github.com/in2code-de/femanager/blob/develop/Documentation/Upgrade/Index.rst

**Comment by ingeniumdesign** [comment]
Thanks, but i check the HTML Templates and i test with the org. Ext.-Files!
The Validation.js is from the Extension.

my test is only with the Ext.-Files!
The Problem is only in the "Invitation password request" => typoscript => validationEdit

please check this templates/javascript for this part.
Thanks!
