### ISSUE TITLE
Error on "user edit"

### ISSUE THREAD

**Issue by kszymukowicz** [in2code-de/femanager#129]
When editing usr profile I am getting following error on TYPO3 9.5 with latest version:
 
```
(1/1) Error
Call to undefined method TYPO3\CMS\Core\Database\ConnectionPool::exec_SELECTquery()

in /Volumes/Data/www/workspace-typo3/projects/projectors-fm/typo3conf/ext/femanager/Classes/Utility/UserUtility.php line 290
    {
        $select = 'ses_id';
        $from = 'fe_sessions';
        $where = 'ses_userid = ' . (int)$user->getUid();
        $res = self::getDatabaseConnection()->exec_SELECTquery($select, $from, $where);
        $row = self::getDatabaseConnection()->sql_fetch_assoc($res);
        return !empty($row['ses_id']);
    }
```

**Comment by sbusemann** [comment]
@kszymukowicz I added a bugfix in the development branch and tested it in my environment. Can you please verify it in your setup

**Comment by kszymukowicz** [comment]
@sbusemann 
Tnx for adding bugfix so fast. 
I tested and its working ok in my setup.

**Comment by TheNaderio** [comment]
I can confirm the error and also the fix. Thx

**Comment by sgrossberndt** [comment]
Bugfix is https://github.com/in2code-de/femanager/commit/d291afb1a243e778554c6f35120d32ed57a2b0bb
