### ISSUE TITLE
Captcha "Field could not be validated" in 4.2.5

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/femanager#133]
Hi,
I will get the Error "Field could not be validated" when using the captcha (with the original partials).

**Comment by stephangrass** [comment]
`additionalAttributes="{data-validation: 'captcha(1)'}"` will work!
Thanks!

**Comment by stephangrass** [comment]
`additionalAttributes="{data-validation: 'captcha(1)'}"` will NOT work!

Then there are no errors, but the captcha will not be checked.

**Comment by sbusemann** [comment]
this issue won't be fixed in V4 Branch anymore.
