### ISSUE TITLE
Form error: Field names not translated

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#137]
I get the following flash messages, where the field names are not translated:

Username: Hierbei handelt es sich um ein Pflichtfeld
Password: Hierbei handelt es sich um ein Pflichtfeld
LastName: Hierbei handelt es sich um ein Pflichtfeld

TYPO3 8.7.24
femanager 4.2.5

**Comment by klodeckl** [comment]
Fix:
<f:translate key="tx_femanager_domain_model_user.{error.code}" />
instead of
<femanager:misc.upper string="{error.code}" />:

**Comment by dahaupt** [comment]
@klodeckl **Thank you** for already providing a solution. I quickly created a pull request.
