### ISSUE TITLE
JS validation 5.0.0 small bug (+solution)

### ISSUE THREAD

**Issue by Zillion01** [in2code-de/femanager#138]
Validation.js line 90 should be
`		var url = Femanager.getBaseUrl() + '?type=1548935210';
`
Instead of 
`		var url = Femanager.getBaseUrl() + 'index.php' + '?type=1548935210';
`

Else post will be (in console) 
`POST https://mysite.test/index.php////////////////////?type=1548935210 
`
TYPO3 9.5.4

**Comment by dahaupt** [comment]
@Zillion01 Thanks for sharing your solution as I also ran into this issue today. I hope you won't mind that I've created a PR with your solution to quickly solve this!

**Comment by tomgloeckler** [comment]
Thank you @dahaupt !
