### ISSUE TITLE
Wrong release date for 5.0.0 in README.md

### ISSUE THREAD

**Issue by sgrossberndt** [in2code-de/femanager#139]
While https://github.com/in2code-de/femanager/releases/tag/5.0.0 was tagged on `2019-02-01` the README.md in https://github.com/in2code-de/femanager#changelog claims it was released on `2018-05-11`

**Comment by dahaupt** [comment]
Will be fixed by #140.

**Comment by sgrossberndt** [comment]
Merged in https://github.com/in2code-de/femanager/commit/0fe3ceaa8c805dc98f2797f8431d11241d0ebd3d
