### ISSUE TITLE
Javascript validation error

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#141]
I get an error when using the javascript validation on required fields, but no error reason:
<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<h4>Fehler</h4>
			
		</div>

I just “solved“ it via 
page.includeJSFooter.femanagerValidation >

TYPO3 8.7.24
femanager 4.2.5

**Comment by sbusemann** [comment]
@klodeckl this solves the problem for you, by disabling JS Validation in the Frontend. The cause behind is most probably, that JS validation is not working due to the last security update. Please check your html template, if you want to use JS validation.
