### ISSUE TITLE
Backport fix for #129 Error on "user edit" to 4.2.x

### ISSUE THREAD

**Issue by Xarno** [in2code-de/femanager#144]
The same error that was described in #129 happens in 4.2.5 for our Typo3 (8.7.24). 
The same fix for 5.0.0 (https://github.com/in2code-de/femanager/commit/d291afb1a243e778554c6f35120d32ed57a2b0bb) works on 4.2.5.

**Comment by sbusemann** [comment]
Version 5.1.0 of femanager works now with TYPO3 8 LTS, so I can close this ticket.
