### ISSUE TITLE
New logic exception ignores content from DCE

### ISSUE THREAD

**Issue by Xarno** [in2code-de/femanager#145]
femanager Version 4.2.5

The LogicExeption is raised if the femanager Plugin is added to the page via Dynamic Content Elements (DCE) which is not correct. Commenting the Check and Exeption let the validation proceed as expected.

For reference:
AbstractValidator.php
```php
    protected function checkAllowedControllerName(string $controllerName)
    {
        $pluginRepository = ObjectUtility::getObjectManager()->get(PluginRepository::class);
        $pageIdentifier = FrontendUtility::getCurrentPid();
        if ($pluginRepository->isPluginWithViewOnGivenPage($controllerName, $pageIdentifier) === false) {
            throw new \LogicException('ControllerName is not allowed', 1541506524);
        }
    }
```

**Comment by sbusemann** [comment]
The check is a security feature. Disabling it, might work then for DCE, but opens up your site. DCE is not a core feature of TYPO3. You can help to support it, by offering a merge request. As I have no experience with DCE, I won't offer it by myself.

**Comment by swisschocolate** [comment]
Same problem if plugin is inserted by typoscript, e.g to include a registration form on every page. How to avoid the exception in this case?

**Comment by Patta** [comment]
I can confirm the exception, if the plugin is added with CType shortcut to include a edit form on multiple sites.

TYPO3 9.5.18
PHP 7.3.17
Composer mode
femanager 5.2.0

**Comment by sbusemann** [comment]
There is no short term solution for the moment
