### ISSUE TITLE
Validation.min.js ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Pekkonen** [in2code-de/femanager#154]
I try to configure new femanager 5.0.0 on TYPO3 9.5.5 and have problem with registration action.
After press a button "Register" I see in console problem with validation:
Validation.min.js?1554499403:1 Error: The called url is not available - if you use TYPO3 in a subfolder, please use config.baseURL in TypoScript
jquery-3.3.1.min.js:2 POST http://example.com/index.php////////////////////?type=1548935210 net::ERR_TOO_MANY_REDIRECTS
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
n @ Validation.min.js?1554499403:1
(anonymous) @ Validation.min.js?1554499403:1
In Network tab I see how in URL adding slashes...
I try add  config.baseURL  to root page setup, but with no success.
Anybody have same error?

**Comment by Pekkonen** [comment]
For all who want fix this bug - check this link https://github.com/in2code-de/femanager/pull/142

**Comment by sbusemann** [comment]
this is solved in version 5.1.0
