### ISSUE TITLE
Usergroup

### ISSUE THREAD

**Issue by michaelpeuser** [in2code-de/femanager#158]
Hi Alex and Stefan, 
I tried to give an user the possibillity to change the Usergroup in a TYPO3 9.55 with PHP 7.2.x, but I get this message: 
The Fluid template files "/www/htdocs/w00a0b04/t9/typo3conf/ext/femanager/Resources/Private/Partials/Fields/Profile.html", "/www/htdocs/w00a0b04/t9/typo3conf/ext/femanager/Resources/Private/Partials/Fields/Profile" could not be loaded.

And: The way to extend femanager with an own extension (works fine with TYPO3 7 & 8) now I can't use it. The workaround: "https://stackoverflow.com/questions/45563671/how-to-extend-femanager-controller-under-php-7/45564378" didn't work in my installation.

**Comment by sbusemann** [comment]
Did you check your html templates? Did your solution works with TYPO3 8 and the latest femanager release (with the security update)?

**Comment by michaelpeuser** [comment]
I'll try the new version and give you feedback.
