### ISSUE TITLE
Error after Invitation

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#161]
After a Invitation from FE:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function setDisable() on null | Error thrown in file .../typo3conf/ext/femanager/Classes/Controller/InvitationController.php in line 120. Requested URL: URL...?tx_femanager_pi1%5Buser%5D=127&tx_femanager_pi1%5Bhash%5D=6953efef160d1721&tx_femanager_pi1%5Bcontroller%5D=Invitation&tx_femanager_pi1%5Baction%5D=edit&cHash=ca0d2c6e219eb7043765e3d6394767e1`

**Comment by sbusemann** [comment]
[](url)
