### ISSUE TITLE
Resend confirmation mail

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#162]
Hi, the Resend confirmation mail dont works with the Invitation Mode.
If you use the Invitation and will be send a Resend confirmation mail, the links dont work.

What can i do?

**Comment by marexx** [comment]
Maybe the same issue, when i click the "resend link" in the BE, the mail is send, but the link looks like this:
/typo3/index.php?M=web_FemanagerM1&moduleToken=b59a09f250af91b3d8c61255b5f65e16822d7060&id=17&tx_femanager_pi1%5Buser%5D=53&tx_femanager_pi1%5Bhash%5D=0fb1a7482882d279&tx_femanager_pi1%5Bstatus%5D=userConfirmation&tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New
and therfore doesen't work..

**Comment by sbusemann** [comment]
@marexx which TYPO3 version do you use?

**Comment by marexx** [comment]
TYPO3 8.7

**Comment by sbusemann** [comment]
This is solved in V8 (TYPO3 12)
