### ISSUE TITLE
Link to documentation valid?

### ISSUE THREAD

**Issue by beyring** [in2code-de/femanager#169]
Hi,

I wanted to checkout the documentation following that link in the readme:

Please look at the manual for a big documentation at https://docs.typo3.org/typo3cms/extensions/femanager/

But there is just the link back to this repository. 

Can I find an online version somewhere?

Thanks in advance,
Ben

**Comment by sbusemann** [comment]
dear Ben, this is a known issue and will be fixed in our next release.

**Comment by beyring** [comment]
Thanks very much.

Stefan Busemann <notifications@github.com> schrieb am Mo., 20. Mai 2019,
16:09:
