### ISSUE TITLE
invitation - validationEdit - Password Repeat

### ISSUE THREAD

**Issue by ingeniumdesign** [in2code-de/femanager#171]
The Password Repeat dont works in invite-mode!

> password {
>   required = 1
>   min = 6
> }
> password_repeat {
>   required = 1
>   sameAS = password
>}

"Password: Passwort und Wiederholung stimmen nicht überein"

**Comment by pixeldesu** [comment]
I tried replicating this with this exact configuration, including the casing, and this works in Femanager 8.2.0.

**Comment by Mordef** [comment]
same here, TYPO3 v12.4.34 and femanagr v8.3.0
```
                password {
                    min = 8
                }
                password_repeat {
                    required = 1
                    sameAs = password
                }
```
Allways invalid
