### ISSUE TITLE
Image upload only allows 1 file

### ISSUE THREAD

**Issue by JeppeDonslund** [in2code-de/femanager#174]
I have set UploadAmount to 5, but I can only upload 1 image in user create or user edit.

**Comment by sbusemann** [comment]
this case is not intended and currently not supported.

**Comment by JeppeDonslund** [comment]
It looks like it was possible in version 1.0.11 according to this: https://extensions.typo3.org/extension/femanager/

But no longer?

**Comment by sbusemann** [comment]
Yes, in the past (before FAL was introduced), but atm not.
