### ISSUE TITLE
Allow redirect to another page / action after creation

### ISSUE THREAD

**Issue by DanielSiepmann** [in2code-de/femanager#178]
Currently the controller hard coded redirects to `new` action when a new user was created. That's not what our customers need and provides bad UX, as the user already created an account. Instead configuring a redirect to keep user in flow would be better. E.g. allow to configure a page uid which provides the login, so users can login once they confirmed the account.

**Comment by sbusemann** [comment]
you can set up redirects via typoscript.

Example for invitation, if a user deleted the profile:

```
plugin.tx_femanager.settings.invitation {
	# redirect user after profile delete (from email)
	redirectDelete = TEXT
	redirectDelete {
		typolink {
			parameter = 6070
			returnLast = url
		}
	}
}
```

**Comment by DanielSiepmann** [comment]
Then let's reopen this one as missing implementation for following setup:

5.1.1, `new.confirmByAdmin` set to an email via Flexform. In this flow, there is no call to `redirectByAction` which would handle the configuration. Just a plain `$this->redirect('new')`: https://github.com/in2code-de/femanager/blob/5.1.1/Classes/Controller/NewController.php#L276
