### ISSUE TITLE
blur() event doesn´t fire upon checkbox validation

### ISSUE THREAD

**Issue by boettner-it** [in2code-de/femanager#184]
Tested in FF 69, IE 11 and some undefined Chrome version of a customer. 

Fix: use change() for checkboxes.

Wasn´t able to create a pull request but could do so to offer a fix

```javascript
$('input[type=checkbox]').change(function() {
	validateField($(this), false); // validate this field only
});
```

**Comment by sbusemann** [comment]
@boettner-it can you describe the problem more detailed?

**Comment by boettner-it** [comment]
It´s been a while...

Looking at https://github.com/in2code-de/femanager/blob/934e0ead2099381749de2731812a2a15c1490c66/Resources/Private/JavaScript/Validation.js#L109

the issue seems to be none anymore.

**Comment by sbusemann** [comment]
thx for the feedback!
