### ISSUE TITLE
Users get refused automatically 

### ISSUE THREAD

**Issue by jayhall69** [in2code-de/femanager#194]
This issue is really hard to track down. After user confirmation they get the refusal email almost immediately, sometimes it takes 1 or 2 minutes. This happens *before* the admin can even decide on the confirmation. The profile is already deleted when the admin receives the confirmation email.

**This is my configuration:**
typo 8.7.20
femanager 4.2.2
Registration must be confirmed from sender CHECKED 
Registration must be confirmed from an admin (add one or more emails)
registration@customer.com
Notify admin on registration (add one or more emails)
registration@customer.com

Even stranger it is when i use another email (i.e. my own) as admin email. The process seems to work.

I have looked into the code deeply, figuring out that the refusal won't happen without any admin action. At some point 
` function statusUserConfirmationRefused`
has been executed automatically. There is no AAC class set up.

An excerpt from the db log illustrates the issue:

```
22-11-19 10:55	Registration refused by admin
22-11-19 10:55	Registration confirmed by admin
22-11-19 10:55	Registration confirmed by user
22-11-19 10:52	Profile creation request

22-11-19 09:54	Registration refused by admin	
22-11-19 09:53	Registration confirmed by admin	
22-11-19 09:53	Registration confirmed by user
22-11-19 09:53	Profile creation request
 	
22-11-19 09:47	Registration refused by admin
22-11-19 09:47	Registration confirmed by admin	
22-11-19 09:45	Registration confirmed by user
22-11-19 09:45	Profile creation request

22-11-19 09:31	Registration refused by admin 	
22-11-19 09:31	Registration confirmed by admin
22-11-19 09:31	Registration confirmed by user
22-11-19 09:31	Profile creation request
```

Another topic: how can we inform the user that his profile has finally been activated ? I haven't found any option for this.

Thanks a lot for your hints, J

**Comment by sbusemann** [comment]
I can not reproduce this behaviour. The auto approve (or decline) function, was introduced in femanager 5.

A final message to the user (after admin activation) can be activated via TypoScript (new.email...)

We won't do any further changes for the 4.x Branch
