### ISSUE TITLE
terms field is not being validated

### ISSUE THREAD

**Issue by MrMooky** [in2code-de/femanager#201]
I added three new validation rules for `firstName`, `lastName` and `terms`. The first two validate just fine, but even if I check the terms checkbox, it throws an error. Is there any other validation rule I should use? `required = 1` makes sense to me.

**Update**: I just realised that `firstName` and `lastName` won't validate either. So, while it makes the fields required, it is not updating when they are filled.

```
plugin.tx_femanager.settings.new.validation {
    firstName {
        required = 1
    }
    lastName {
        required = 1
    }
    terms {
        required = 1
    }
}
```

<img width="458" alt="Screen Shot 2019-11-27 at 16 14 40" src="https://user-images.githubusercontent.com/3603346/69735482-0ac56600-1131-11ea-9ed2-e95622f962f6.png">

**Comment by MrMooky** [comment]
Update: I just realised that `firstName` and `lastName` won't validate either. So, while it makes the fields required, it is not updating when they are filled.

**Comment by sbusemann** [comment]
i use the setting
`plugin.tx_femanager.settings.new.validation {
  terms {
    required = 1
  }
}

`

and it works in the test environment.
