### ISSUE TITLE
Security vulnerability: Insecure Direct Object References

### ISSUE THREAD

**Issue by boeschung** [in2code-de/femanager#207]
In a local project, we use a Typo3 installation together with the extensions femanager and femanager_dmail_subscribe (each without customizing), which offers the possibility to subscribe to a newsletter. For this, a user must select a newsletter category, specify his email address and confirm a captcha. After logging in, the user receives a confirmation email based on the double opt-in principle. If the subscription is confirmed by the user via the link, the subscription element will be activated and the user will receive the newsletter from then on.

In addition to being able to delete the subscription, the newsletter also includes a link to change the subscription profile. Here the user can only adapt the newsletter category, more is not possible for the user.

Everything works as expected and desired. However, an internal pentest now had a scenario where it was possible to change the subscription profile of another user - just by changing the UID! Since the UID is assigned on an ongoing basis, guessing more valid UIDs is pretty easy. Such vulnerability is called "Insecure Direct Object References".

The vulnerability can e.g. be reproduced by using a proxy that intercepts all requests. For this Burpsuite Community Edition was used and configured as a proxy. The attack was as follows:

Preparation:

Create 2 newsletter subscriptions with different mail addresses:
- test1@example.com (UID 1)
- test2@example.com (UID 2)

Attack:

- Log in to "test1" via the link in the newsletter in the browser
- Change newsletter category in the browser
- Call Burp and activate "Intercept is on"
- Click on "Change profile" in the browser
- Burp intercepts the request
- Change the UID from 1 to 2 in Burp and send request in Burp
- Now log in the account "test2" via the link in the newsletter in the browser
- The changes were now made on "test2" and not on "test1"

Apparently, the UID transmitted in the request is not checked for validity, but only "passed through". Either an additional check of the UID should take place here, or the UID should not be transmitted and verified via the session.

Typo3: 8.7.29
femanager: 4.2.4
femanager direct mail subscription: 2.1.2

**Comment by sbusemann** [comment]
There is an update in work, which will change the behaviour.
