### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by typo3rel** [in2code-de/femanager#218]
Hi,

something strange was going on with our front-end users and seminar participants etc:

In UserRepository.php at line 300

```
    /**
     * Find All
     *
     * @param string $mail
     * @return QueryResultInterface|array
     */
    public function findFirstByEmail(string $mail)
    {
        $query = $this->createQuery();
        $this->ignoreEnableFieldsAndStoragePage($query);
        $and = [$query->equals('txFemanagerConfirmedbyuser', false)];
        $and[] = $query->like('email', '%' . $mail . '%');
        $query->matching($query->logicalAnd($and));
        $query->setOrderings(['uid' => QueryInterface::ORDER_DESCENDING]);
        return $query->execute()->getFirst();
    }
```
used by resendConfirmationMailAction() in NewController.

`
$this->ignoreEnableFieldsAndStoragePage($query);
`
and  
`
$and[] = $query->like('email', '%' . $mail . '%');
`
didn't seem the best idea

Thank you

**Comment by spoonerWeb** [comment]
Can you tell more details about the "strange behaviour"?
What is happening? What is the problem with removing enableFields and storagePage when searching for email?

**Comment by typo3rel** [comment]
Oh.. i think the problem is/was "like" matches multiple emails and the wrong persons got that mail

**Comment by typo3rel** [comment]
this resulted in > statusUserConfirmationRefused > $this->userRepository->remove($user);
i think that was the problem

**Comment by typo3rel** [comment]
ah and we have users multiple times in different sysfolders for seminar registrations e.g.

**Comment by spoonerWeb** [comment]
We need to set this with a global configuration option, that's a bigger thing.

**Comment by spoonerWeb** [comment]
See: #373
