### ISSUE TITLE
Feature: Update of latitude / longitude after address change

### ISSUE THREAD

**Issue by Hobokens** [in2code-de/femanager#219]
Hi,
I use TYPO3 v9.5.13 and femanager v5.2.

When users change their addresses in frontend (street, zip, town) with femanager the latitude and longitude are not updated in the table fe_users. Therefore the new addresses will be displayed with the old geo-coordinates in plugins that display addresses of fe_users e.g. on a google map.

Regards
Hobokens

**Comment by spoonerWeb** [comment]
Neither the TYPO3 Core nor the `femanager` extension provide geo-coordinates. We can't update fields we don't use. This must be done by the extension you use for this geo-coordinates.
