### ISSUE TITLE
No translation in Typo3 9.5.14

### ISSUE THREAD

**Issue by astoun** [in2code-de/femanager#225]
I have a problem with a German translation for femanager in Typo3 9.5.14
If I try to add a language pack under Maintenance/Manage Language Packs/femanager I get the message: 1 language pack not available
And in frontend there is only English labels and messages for the registration form and emails.
How can I get another language?
Thank you!

**Comment by sbusemann** [comment]
this is not a problem of femanager itself. This seems to be an issue in the Core itself.
