### ISSUE TITLE
Do not use GET-requests to change the users state

### ISSUE THREAD

**Issue by knusperpixel** [in2code-de/femanager#226]
Currently the extension sends e-mails containing plain links to confirm a registration, delete a profile or admin-confirm a user.

As these actions change the users state, they should use a POST-request..

**Comment by spoonerWeb** [comment]
Can you tell me how to set links using a POST request into an email? @knusperpixel

**Comment by knusperpixel** [comment]
@spoonerWeb You will probably need to link to some kind of confirmation page which holds a form that sends the post request.

**Comment by sbusemann** [comment]
@knusperpixel reacting on data via get params is the default behaviour of TYPO3 / Extbase. You can write an own middleware to change this behaviour.
