### ISSUE TITLE
Compatibility to TYPO3 10 LTS

### ISSUE THREAD

**Issue by janhelke** [in2code-de/femanager#230]
Do you have any prediction, when the femanager will be compatible with v10?

**Comment by sbusemann** [comment]
The release will come soon. Please start testing the v10-support branch.

**Comment by prdt3e** [comment]
Replace config.persistence.classes typoscript configuration

ext_typoscript_setup.txt

[87623](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html)

**Comment by BastianBalthasarBux** [comment]
Frontend Error with latest version on TYPO3 v9 LTS: EventDispatcherInterface does not exist.

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html
