### ISSUE TITLE
All fields are always validated

### ISSUE THREAD

**Issue by nollm** [in2code-de/femanager#233]
I only want to change the password on one page.
Therefore I have included fe_manager on this page.
In the settings I have chosen Edit and as fields only the password field.
If I have activated a validation for the username in TypoScript and the current username of my user does not fulfill this rule, I cannot change the password.
`plugin.tx_femanager.settings.edit.validation.username.email = 1`

**Comment by Mordef** [comment]
same here.
The returnvalue from ajax is not parsed as json.  
Try this in femanager\Resources\Public\JavaScript\Validation.min.js  
```  
... success:function(e){e=JSON.parse(e); ...  
``` 
Works for me

**Comment by droomdre** [comment]
i think u need to remove the required for edit. something like:
plugin.tx_femanager.settings.edit.validation.username.required= 0

**Comment by nollm** [comment]
That is my workaround as well.
However the bug still exists.
I would expect no validation of a field if it is not selected. No matter what is defined with TypoScript.

**Comment by sbusemann** [comment]
the validation is done for the full object and setting which apply to the page. You need to configure it.
