### ISSUE TITLE
When both user and admin confirmations are enabled, admin confirmation requests are sent out twice

### ISSUE THREAD

**Issue by naglfar** [in2code-de/femanager#240]
Currently testing on the v10 branch, I noticed the admin was getting confirmation mails both when the user registered and after the user confirmed via email link. I think the expected behavior would be to only send one admin confirmation after the user confirmed.

Since I'm extending fields with my own extension I've been overwriting the createRequest method of the NewController and adding a check to block the admin confirmation request in this case, i.e.:

``` php
if (empty($this->settings['new']['confirmByUser']) && !empty($this->settings['new']['confirmByAdmin'])) {
```

**Comment by clivebeckett** [comment]
I can confirm this behaviour for T3v9 and femanager 5.3.0 – and I wouldn’t know how where to change that behaviour without meddling with the original code.

Another problem with this is that login for a new user works as soon as an admin has confirmed the account, even if the user hasn’t confirmed their address.

**Comment by wrock** [comment]
I can confirm this behaviour for T3v9.5.20 and femanager 5.3.1

**Comment by clivebeckett** [comment]
> Are you also in an MS environment?

Nope :) My website is running on Ubuntu Linux with Apache Webserver. The links in the e-mails are direct links to the page on the website which contains the plugin.

**Comment by boettner-it** [comment]
Sorry, I wasn´t specific enough, I meant a client-side MS environment. Phishing protection is done in the mail client the notification mails are opened with.

**Comment by seitenformate** [comment]
I can also confirm this. TYPO3 9.5.21, femanager 5.3.1 and 5.4.0, Linux Apache system

**Comment by colorcube** [comment]
version 6.1.2

- user registers
- user gets confirmation email and admin gets also confirmation email (admin shouldn't get one)
- after user confirms, the admin gets again confirmation email

I think a return (or 'else') is missing.
On the other hand I have not enough insight to understand how this is supposed to be working.

NewController:
```
    protected function createRequest(User $user)
    {
        $user->setDisable(true);
        $this->userRepository->add($user);
        $this->persistenceManager->persistAll();
        $this->logUtility->log(Log::STATUS_PROFILECREATIONREQUEST, $user);
        if (!empty($this->settings['new']['confirmByUser'])) {
            $this->createUserConfirmationRequest($user);
            $this->redirectByAction('new', 'requestRedirect');
            return; // <----------------------------------------------------------------- missing
        }
        if (!empty($this->settings['new']['confirmByAdmin'])) {
            $this->createAdminConfirmationRequest($user);
            $this->redirectByAction('new', 'requestRedirect');
        }
    }
```

**Comment by spoonerWeb** [comment]
Agreed. Basically it should not go forward in the code after `redirectByAction()`, but as there are some issues with the redirect (see #270) it could happen that there is no redirect.

To be sure we should add this `return;`
