### ISSUE TITLE
All input fields with error

### ISSUE THREAD

**Issue by Terminator81** [in2code-de/femanager#242]
![grafik](https://user-images.githubusercontent.com/16563785/86639946-1851a100-bfda-11ea-9448-3c3a8f404628.png)

Hello, everyone,

As you can see, I get an "undefined" error after each field after the input - what am I doing wrong?

**Comment by Patta** [comment]
Try version 5.3 or 6.0. this should be related to #202

**Comment by Terminator81** [comment]
ok thanks fixed :)
