### ISSUE TITLE
Missing translation in TYPO3 V10 and femanager6.0.1

### ISSUE THREAD

**Issue by typo3-solution** [in2code-de/femanager#250]
Hi,
i miss the translation in TYPO3v10 for this extension. Is this a simple missconfiguration oder is the (de/it/fr) translation missing? 
If the translation is missing, i will create it.
Simon

**Comment by TheNaderio** [comment]
Same here - cannot download translations with the "Manage Language Packs"-Module

**Comment by typo3-solution** [comment]
Translation for DE,IT,FR
[feManager.zip](https://github.com/in2code-de/femanager/files/5055760/feManager.zip)

**Comment by spoonerWeb** [comment]
In TYPO3 v10 they switched to CrowdIn only. The translation are not fetched from the old Pootle server anymore.
To activate and migrate the translations for working in v10, there is a guide here: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.html#crowdin-extension-integration

**Comment by spoonerWeb** [comment]
@sbusemann What help do you need? The docs are linked in my comment. Setup can only be done by GitHub repo owners.

**Comment by sbusemann** [comment]
@spoonerWeb yes, lets do it!

**Comment by sbusemann** [comment]
Support for Crowdin is now working
