### ISSUE TITLE
No notification to user after admin confirms registration in backend

### ISSUE THREAD

**Issue by RobertSK** [in2code-de/femanager#251]
If admin confirms with link in email a notification is sens to the user.  
If admin confirms in backend, tab "Registration" -> Checkbox "Registration confirmed by admin"  [tx_femanager_confirmedbyadmin] no notification is send.  
Typo3 9.5.6  
femanager 5.2.0

**Comment by Patta** [comment]
It seems that this is fixed in v6 only.

**Comment by sbusemann** [comment]
It can be backported with payed support https://www.in2code.de/en/agency/typo3-extensions/support-und-sponsoring-for-typo3-extensions/ or if some creates a PR
