### ISSUE TITLE
Error message after confirm registration

### ISSUE THREAD

**Issue by mmasmoudi** [in2code-de/femanager#259]
After the registration of my account I get an E-Mail where I have to confirm the registration.
When I click on the button the "Meine Beiträge" I get an error message:

**forum.**/registrierung/?tx_femanager_pi1%5Baction%5D=createStatus&tx_femanager_pi1%5Bcontroller%5D=New&cHash=fe901085792ffaafe5cbed6d0e816675
![FireShot Capture 112 - Registration process bug](https://user-images.githubusercontent.com/6702619/91151493-075e0b80-e6be-11ea-91d2-a240968130cb.png)

**Comment by spoonerWeb** [comment]
Which `femanager` version do you use?

**Comment by sbusemann** [comment]
no feedback received
