### ISSUE TITLE
Image upload broken since update from 5.2.0 to 5.3.1

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#263]
Hello,

after updating the extension I get an error message when uploading an image:
File /path/defined/in/constants/filename.jpg/ does not exist

After downgrading back to 5.2.0 everything works again.

(TYPO3 8.7.32, PHP 7.3, Debian 10)

**Comment by sbusemann** [comment]
Sorry I can not reproduce it in the current version. If you need a backport or support please use https://www.in2code.de/en/agency/typo3-extensions/support-und-sponsoring-for-typo3-extensions/
