### ISSUE TITLE
"Login As" from backend with rootpage type shortcut

### ISSUE THREAD

**Issue by cehret** [in2code-de/femanager#264]
Hello,

I want to use the "Login As" function from the backend. My root page is a shortcut of the login page (readable by everyone). If I click on "Login As" the login page is opened in a new tab but the user is not logged in.
If I change the type of the root page to "normal" it is working.

I changed the UserBackend/List.html to link directly to the login page:

`	<a href="/index.php?id=35&type=1548943013&tx_femanager_pi1[user]={user.uid}" `

Now I need two times to log the user in. The first time I click on the "Login As" link, the login page is opened but the login form is shown - the user ist not logged in. I close the tab and click again on the "Login As" link - again the login page is opened in a new tab, but this time it shows the logged in user. I don't need to use the same user for my two clicks. The second click is the user who gets logged in ;-)

Any idea how to get this working on the first click and without changing the template?

Thank you

Christian

TYPO3: 10.4.6
femanager: 6.1.0

activating/deactivating "Set cookie on login (experimental)" does not make any difference

**Comment by spoonerWeb** [comment]
Works in current `develop` branch with only one click.

**Comment by cehret** [comment]
I still have this issue. 
TYPO3 10.4.17
FeManager github download today: 6.2.1
tried with basic.setCookieOnLogin  On and off

I have a multi Site configuration:

![image](https://user-images.githubusercontent.com/5031075/122783717-1992e100-d2b2-11eb-8739-25a8e655014e.png)

1. is a structure for one site
2. is the structure for another site. Both sites have FrontendUser storages and an own login page. The root page is a shortcut to the login page.

I'm still facing the same issue: With the untouched femanager I click on "Login as" in the backend module the login page is opened - without any user logged in. 

If I edit the link in UserBackend/List.html including the id to the login page, I have to call the "Login as" link twice - than the user ist logged in.

If I could provide any more useful information please let me know!

**Comment by davdenic** [comment]
I have the same issue
TYPO3 v10 (latest)
FeManager (latest)
PHP 7.4
