### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by webian** [in2code-de/femanager#266]
This https://github.com/in2code-de/femanager/blob/b3183190979fa3bdb953c828b4e18849ceefa5e5/Classes/Controller/NewController.php#L296
is already done here:
https://github.com/in2code-de/femanager/blob/b3183190979fa3bdb953c828b4e18849ceefa5e5/Classes/Controller/NewController.php#L315

**Comment by spoonerWeb** [comment]
The current implementation is not redundant as it could be possible that neither `confirmByUser` nor `confirmByAdmin` is set. Then there is no redirect.
