### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by webian** [in2code-de/femanager#271]
In pages without femanager form is thrown javascript error:
`Uncaught` TypeError: Cannot read property 'dataset' of null`

**Comment by rintisch** [comment]
I get `Uncaught TypeError: document.querySelector(...) is null` which is thrown in `Femanager.min.js`. 

Screenshot:
![grafik](https://user-images.githubusercontent.com/44193208/92379424-bdd2df00-f107-11ea-9982-e1f0864eef57.png)

I cannot find this directly in the file, should be around column 2074 but it's not there. Can this be added somehow when using webpack?

**Comment by luberti** [comment]
We are using Femanager 6.1.1 and getting the same exception of @rintisch .
Lookin at the unminifiedversion of Femanager.min.js available in github the bug has been resolved but the minified versione that you can get downloading from github or TER is still bugged

**Comment by spoonerWeb** [comment]
No JS error in current `develop` state.
