### ISSUE TITLE
JavaScript error in FeManager.js since 5.4.0

### ISSUE THREAD

**Issue by FailXSiegen** [in2code-de/femanager#278]
"Uncaught TypeError: Cannot read property 'dataset' of null"
in FeManager.js
2:     var labels = JSON.parse(document.querySelector('.tx-femanager[data-labels]').dataset['labels']);

Tries to select element which doesn't exist. Need check if .tx-femanager exists

**Comment by Patta** [comment]
@FailXSiegen if you overwrite the default layout, check if you have applied the latest changes from 5.4.0 https://github.com/in2code-de/femanager/blob/a71c631ab22f09a5b82666944a5418cd8927cf34/Resources/Private/Layouts/Default.html

**Comment by FailXSiegen** [comment]
@Patta Thx for your comment/review. We don't override the Layouts/Default
On the page where the registration form exists there is no JS error. The error exists on any other page due to the non-existing .tx-femanager html.
Easy/quick fix would be to check if the element exists in an if condition

**Comment by Patta** [comment]
@FailXSiegen I understand. A further and recommended way is to include the femanager assets only on the pages where the femanager plugins are placed. e.g. with a fluid inlude file viewhelper in the default layout.

**Comment by FailXSiegen** [comment]
@Patta 
The issue is in a 5.4 version with no vhs dependencyto use the asset.script and no dependency to 10.4 for asset.script support.
Furthermore there is no instruction to use the typoscript includes in an +ext only context.

Is it that big of a problem to wrap the js in an if-condition or do we really need to discuss all other possibilities for a workaround of a side-wide effecting js-error?

**Comment by medarob** [comment]
I can confirm the same error in TYPO3 9.5.22 with femanager 5.4.
A fix would be great.

**Comment by grischpel** [comment]
Bugfix: 
` var t;
  if (document.querySelector(".tx-femanager[data-labels]") != null) {
    t = JSON.parse(document.querySelector(".tx-femanager[data-labels]").dataset.labels);
  } else {
    t = [];
  }`

**Comment by swisschocolate** [comment]
+1 
TYPO3 9.5.22, femanager 5.4.1

**Comment by sbusemann** [comment]
fixed in develop branch and 5.x branch

**Comment by grischpel** [comment]
> Bugfix: (line 65)
> ` var t;`
> ` if (document.querySelector(".tx-femanager[data-labels]") != null) {`
> ` t = JSON.parse(document.querySelector(".tx-femanager[data-labels]").dataset.labels);`
> ` } else {`
> ` t = [];`
> ` }`

Attention!!! 
These Fix is must be fixed, too....

this is the correct fix:


` if (document.querySelector(".tx-femanager[data-labels]").length > 0) {`

**Comment by sbusemann** [comment]
@grischpel can you explain, why this:
`if (document.querySelector(".tx-femanager[data-labels]").length > 0) {`

should be correct? 

`if (document.querySelector(".tx-femanager[data-labels]") != null)`

seems to work

**Comment by grischpel** [comment]
it work both 😂 but as i fixed it in an other project, i did a mistake in the if question.... so i tried with `if (document.querySelector(".tx-femanager[data-labels]").length > 0) {`
and it also works... 
it was totaly my mistake.... so please ignore my post 🤷‍♂️🤪
