### ISSUE TITLE
Backend user confirmation fails

### ISSUE THREAD

**Issue by boettner-it** [in2code-de/femanager#280]
Hi all,

the BE request for confirming user registration fails. The fetched frontend request returns the whole page as HTML where a JSON result is expected. Does anything have to be configured regarding routing in config.yaml or anything in Typoscript? I couldn´t find any hints in the docs or changelog.

Robert.

TYPO3 10.4.8
femanager 6.1.0

**Comment by spoonerWeb** [comment]
I can confirm this and would recommend to generally build these kind of requests with Middleware, see #374.

**Comment by sbusemann** [comment]
duplicates #374
