### ISSUE TITLE
missing dependency with static_info_tables

### ISSUE THREAD

**Issue by TeddyBears** [in2code-de/femanager#281]
The dependency with static Info Tables are not set in composer.json or ext_emconf.php files
So when activate the plugin the website displays a error :

```php
Cannot autowire service "In2code\Femanager\DataProvider\CountryZonesDataProvider": argument "$countryZoneRepository" of method "__construct()" references class "SJBR\StaticInfoTables\Domain\Repository\CountryZoneRepository" but no such service exists. Try changing the type-hint to "TYPO3\CMS\Extbase\Persistence\Repository" instead.
```

And we have to remove femanager from PackageStates.php file to have access to BE

**Comment by sbusemann** [comment]
which version of TYPO3 and FE Manager do you use (i guess TYPO3 v10 and femanager 6.x)

**Comment by spoonerWeb** [comment]
I get the same error on TYPO3 v10 and femanager 6.1.0. When you use code from `static_info_tables`, it must be in composer.json and ext_emconf.php as dependency.

**Comment by TeddyBears** [comment]
Sorry for lait reply. yes i'm using TYPO3 10 and femanager 6.10
