### ISSUE TITLE
Installation width composer leads to Error 500

### ISSUE THREAD

**Issue by roccoh** [in2code-de/femanager#282]
My approach:
1. Installation of TYPO3 10 with composer - everything ok
2. Installation of femanager with composer - the page can no longer be reached (HTTP ERROR 500)

Does anyone know this problem, or to ask it another way: what am I doing wrong?

**Comment by sbusemann** [comment]
Please try to require composer req sjbr/static-info-tables

**Comment by roccoh** [comment]
Hy Stefan
Many thanks for your quick response!!!
That solved it.

**Comment by sbusemann** [comment]
Resolved with https://github.com/in2code-de/femanager/pull/284
