### ISSUE TITLE
Psr\EventDispatcher\EventDispatcherInterface not available in TYPO3 9.5.x

### ISSUE THREAD

**Issue by matin73** [in2code-de/femanager#283]
If I use version 5.4 or 6.0 in TYPO3 9.5.x an error occures, because  PSR is only available in 10

**Comment by sbusemann** [comment]
Version 6.x is only for TYPO3 10.4 
Version 5.4 should work for TYPO3 8 and 9. Can you please try to describe the error more detailed (maybe error message, classname, linenumber?

The TYPO3 Version you are using, FEmanager Version you try to use.

**Comment by matin73** [comment]
please have a look to https://extensions.typo3.org/extension/femanager/ - version 6.0 is also vor 9.5.x (9.5.0 - 10.4.99). maybe you can change it

**Comment by sbusemann** [comment]
yes, this was updated in 6.0.1 - i can not change a release version afterwards.
