### ISSUE TITLE
Directory ".project" leads to huge archives

### ISSUE THREAD

**Issue by mbrodala** [in2code-de/femanager#286]
The `.project` directory of this repository is huge (3,6MB ATM) which in turn leads to huge archives, both on TER as well as Packagist:

```
$ du -sh femanager_6.1.0
5.7M	femanager_6.1.0
$ du -sh femanager_6.1.0/.project
3.6M	femanager_6.1.0/.project
```

Thus this directory should be removed and added to the `.gitignore` (exactly in this order) to reduce the archive size again.

**Comment by sbusemann** [comment]
this is the integrated development setup (Docker, Testdb). I could remove the db and try to store it on another location, but the base setup is needed, to improve the development setup

**Comment by mbrodala** [comment]
@sbusemann At least for Composer you can add the whole `.project` directory to `.gitattributes` since there is no point having this on a production site. This does not affect Git clones for development.

**Comment by tmotyl** [comment]
isn't it already resolved ?
https://github.com/in2code-de/femanager/blob/develop/.gitattributes#L5

**Comment by mbrodala** [comment]
@tmotyl, yes, 11 day ago: https://github.com/in2code-de/femanager/commit/235ae9ed2fdb74f69365121e421f54ca9863c636

So it's basically resolved for Composer dist packages which is enough IMO. :-)

**Comment by vertexvaar** [comment]
I like it when random changes solve random issues :joy:
