### ISSUE TITLE
Exception ChangeClassDatamapPass not found

### ISSUE THREAD

**Issue by Footrotflat** [in2code-de/femanager#288]
I have a new Typo3 installation v10.4.9 with PHP 7.3.22
I'm trying to install femanager v6.1.0 in the Extension Manager (2 attempts).
The installation of femanager v6.1.0 breaks the whole Typo3 installation, nothing works anymore ...

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'In2code\Femanager\DependencyInjection\CompilerPass\ChangeClassDatamapPass' not found | Error thrown in file /home/xxx/www/xxx/htdocs/typo3conf/ext/femanager/Configuration/Services.php in line 10. Requested URL: https://xxx/typo3/index.php?route=%%2Fmodule%%2Ftools%%2FExtensionmanagerExtensionmanager&token=--AnonymizedToken--

**Comment by sbusemann** [comment]
@Footrotflat Please try to require composer req sjbr/static-info-tables

**Comment by Footrotflat** [comment]
Thank you very much.

With the additional definition 'static_info_tables' under dependencies in 'ext_emconf.php' the extension can be installed without any problems.

I noticed that both a TCA migration check and a scan extension files are highly recommended.

![femanager_Scan_Extension_Files](https://user-images.githubusercontent.com/34073135/95342845-24d6e580-08b8-11eb-9d62-341d5277e564.JPG)

![femanager_Check_TCA_Migrations](https://user-images.githubusercontent.com/34073135/95342869-2bfdf380-08b8-11eb-9ad2-cfb29c3221e6.JPG)
