### ISSUE TITLE
Using $this when not in object context / PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by Footrotflat** [in2code-de/femanager#291]
Typo3 10.4.9, PHP 7.3.22, femanager 6.1.0

I have defined the femanager plugin with the invitation option.

Invitation setting: Restrict to one usergroup
Selected items: Username, Gender, Firstname, Lastname
Additional setting: Page with terms and conditions
TypoScript setting: # take username and copy it to the email field

by the way: Both the email field and the username field are listed on the website.

Fields filled out and form sent.
Error occured:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Using $this when not in object context | Error thrown in file /home/xxx/www/xxx/htdocs/typo3conf/ext/femanager/Classes/Utility/LogUtility.php in line 46. Requested URL: https://xxx/xxx/mitarbeiter-einladen?tx_femanager_pi1%%5Baction%%5D=create&tx_femanager_pi1%%5Bcontroller%%5D=Invitation&cHash=123abc

Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method In2code\Femanager\Utility\LogUtility::log() should not be called statically in /home/greatjob/www/jobs-only/htdocs/typo3conf/ext/femanager/Classes/Controller/InvitationController.php line 76

by the way: Record was created in the database.

**Comment by ewokhias** [comment]
I am experiencing this issue too! Have you found any workaround?
