### ISSUE TITLE
View Detial + Edit in same page -> The controller \"Edit\" is not allowed by plugin \"Pi1\"

### ISSUE THREAD

**Issue by jooler** [in2code-de/femanager#292]
TYPO3:10.4.8
Mode:composer
Femanager:6.1.0

insert 2 element by femanager, detial and edit
when I submit in front page, detial view will get error.
I check in logs and give this 
`...ception: The controller \"Edit\" is not allowed by plugin \"Pi1\". Please check for TYPO3\\...`

thanks for your works

**Comment by sbusemann** [comment]
I'm sorry, due to security reasons this is not possible at the moment.
