### ISSUE TITLE
German language is not working for client-side validation

### ISSUE THREAD

**Issue by Midun555** [in2code-de/femanager#293]
[TYPO3 v9.5,14, femanager 5.3.0]
Localization for client-side validation in ext:femanager is not working (German translation). I have both .xlf files. It is **correctly working for serverside validation**.
I guess all coming from the file **ext:femanager/Classes/Domain/Validator/ClientsideValidator.php**.
I need some support.

**Comment by Moongazer** [comment]
Can't confirm that on version TYPO3 v10.4. and femanager 6.1. Also client-side validation messages are translated.

**Comment by SilkeDX** [comment]
I can confirm that for TYPO3 8.7.32 and femanager 5.4.2. It's working for everything except for client-side validation.

**Comment by andre-spindler** [comment]
I can confirm this is broken.

Fetching the Language is not done by checking the LanguageAspect. The FrontendUtility gets the language uid directly from typoscript.
But that doesn't exist any more. Only in some upgraded installations which have not yet been cleand up completely.
![grafik](https://user-images.githubusercontent.com/5618751/119163898-25457a80-ba5c-11eb-9283-571667115c27.png)

**Comment by spoonerWeb** [comment]
Fixed by 65c39ed29297bfc0fd268cd5f714e789b4f7f45a.
