### ISSUE TITLE
femanager 5.4.0: View could not be resolved for action "create" in class "In2code\Femanager\Controller\NewController"

### ISSUE THREAD

**Issue by roccoh** [in2code-de/femanager#295]
My installation
TYPO3: 9.5.22 (composer mode)
femanager: 5.4.0

On creating a new profile, the e-mail's to confirm the registration are both send to the customer and the admin.
The links are working properly (registration completed and confirmed).

Only the registration page shows the message:

Sorry, the requested view was not found.
The technical reason is: No template was found. View could not be resolved for action "create" in class "In2code\Femanager\Controller\NewController".
jquery Error: Cannot read property 'requestContent' of undefined

A reload of the page finally shows the template width the confirmation messages.

On a same installation width TYPO3 10.4.9 (composer mode) and femanager 6.1.0 are no problem detected. All is working as expected.

Has someone an idea, why this problem occurs and how it can be solved?

**Comment by machwatt** [comment]
I have the same problem with TYPO3 v9 and femanager 5.3 and 5.4 – downgrade to 5.2 works for me

**Comment by woodyc79** [comment]
```
plugin.tx_femanager {
    settings {
        new {

			redirect = TEXT
			redirect {
				typolink {
					parameter = 1
					returnLast = url
					#linkAccessRestrictedPages = 1
				}
			}
            # redirect user after profile creation request (only if user confirmation is activated) (could be a PID, URL or fileadmin-Link)
            requestRedirect = TEXT
            requestRedirect {
                typolink {
                    parameter = 1
                    returnLast = url
                    #linkAccessRestrictedPages = 1
                }
            }
}
```

**Comment by roccoh** [comment]
Many thanks for your inputs.
In the meantime I continued my project in TYPO3 10. Therefore I can not verify, what solution would help.
But maybe it can help others...
Best regards and a happy new year.
