### ISSUE TITLE
Download of older versions of femanager

### ISSUE THREAD

**Issue by luberti** [in2code-de/femanager#296]
Hi, we have been put in charge of upgrading an old instance of TYPO3 v6.2 to TYPO3 v10, the actual instance uses femanager 1.3
and there are custom extensions that generates slots listening for signals from various events of femanager.
So, to gradually upgrade to latest version we would need to download and test these custom extensions against intermediate versions of manager, starting with 1.5.2 

Is there a place where we can download this older versions? 

Thanks in advance

**Comment by einpraegsam** [comment]
The place is Github :)

Select a tag and download the extension: https://github.com/in2code-de/femanager

![screenshot-github com-2020 10 21-14_34_34](https://user-images.githubusercontent.com/89055/96720085-9def3600-13aa-11eb-9364-2b91d0a5cdf6.png)

**Comment by luberti** [comment]
Sorry only looked branches.....thanks
