### ISSUE TITLE
Which version to use with TYPO3 V9?

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#298]
Hello,

if using TYPO3 Version 9 should I use femanager in version 5.4.1 or 6.0.0? Because in the comment of 6.0.1 it is said: ”The 6.0 release was falsely tagged with TYPO3 V9 support. This is now corrected.”

**Comment by machwatt** [comment]
v9 is femanager 5.x only, since 6.0 uses PSR calls that are v10 only. that was tagged wrong in 6.0.0 and is corrected in 6.0.1.

**Comment by sbusemann** [comment]
Please use 5.x Branch.

**Comment by klodeckl** [comment]
Thank you!

**Comment by baggyownz** [comment]
hello,

please correct the depends at TYPO3 TER for version 6.0.0, There it says that it's working with TYPO3 9.5.0.

best regards

**Comment by sbusemann** [comment]
The version 6.0 is now removed, due the false dependency
