### ISSUE TITLE
Version 4.5.1: missing redirect to createStatus

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#299]
In version 4.5.1 in Classes/Controller/NewController.php line 67 one line is missing:
$this->redirect('createStatus');

Without the redirect I get an exception that the template for the create action can not be found (create Template does not exist). In version 6.1.1 that redirect is present.

**Comment by machwatt** [comment]
Hey @klodeckl i dont think its the missing redirect since the redirection works another way in 5.x as in 6.x 

i think its an duplicate of #295 and a downgrade to 5.2 worked for me, 5.3 got that error too.

**Comment by sbusemann** [comment]
Is fixed in 5.3.0 

You can sponsor a backport to older versions via https://www.in2code.de/en/agency/typo3-extensions/support-und-sponsoring-for-typo3-extensions/
