### ISSUE TITLE
Registration of new users: validateAction() answers with "Field could not be validated" for every field

### ISSUE THREAD

**Issue by oak-innovation** [in2code-de/femanager#305]
Here is the chain of events I've tracked down:

`UserController::validateAction` does not receive a value for `$plugin`, so this parameter stays 0.
Then, `ClientsideValidator::validateField()` calls `ClientsideValidator::isValidationSettingsDifferentToGlobalSettings()`, 
and there, `$this->getValidationSettingsFromTypoScript()` does not find the `tt_content` record because `$plugin` is 0.
Because of the missing `tt_content` record, `getValidationSettingsFromTypoScript()` does not find a controller name, so it returns empty string; `isValidationSettingsDifferentToGlobalSettings()` returns true, and the so `validateAction()` returns with the mentioned message.

As workaround for now, I've hardcoded the suitable tt_content uid.

As I am new to the code, can you give me a hint where to look? Where should `validationAction()` get its `$plugin` parameter from?

Thank you.

TYPO 9.5.22, femanager 5.4

**Comment by sbusemann** [comment]
Did you try to integrate the plugin only via TypoScript. This is due to security reasons not possible at the moment.

**Comment by woodyc79** [comment]
Hello! I have the same problem, with TYPO3 10 and femanager 6.3.2
I just use the Plugin and get "Field could not be validated"
I debugged into the code and can confirm that $plugin is 0 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/1710712/165818419-bba3098b-fb0d-4846-ab11-83bd0621d3f3.png">

Here is the POST Request:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1710712/165818725-afb774cb-c683-4d3a-a9c0-591f6110c853.png">

I have the "data-femanager.plugin" in the form:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1710712/165819565-c6172e61-6258-4094-aca9-d23fb74694c4.png">

So somehow the validation.min.js script does not read and submit this value.
Regards,
Christian
