### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by marclindemann** [in2code-de/femanager#306]
Is there support for PHP 7.4 ?
Please update Readme 👍

**Comment by sbusemann** [comment]
It is just not tested yet. If someone confirms, that everything works, i can update the readme

**Comment by marclindemann** [comment]
maybe integrate travis?

**Comment by sbusemann** [comment]
if someone® does it

**Comment by dahaupt** [comment]
We've been using the extension with PHP 7.4 for quite a while. I don't know if **everything** works, but we did not encounter any issues yet.

**Comment by Patta** [comment]
Testing since one week local and remote and it works so far (admin confirmation with custom fields, user edit and user list).

**Comment by MaxGTR** [comment]
Errors I encountered with PHP 7.4 are also present in 7.3.

**Comment by spoonerWeb** [comment]
Unit and Behat tests work with PHP 7.4, I think this can be closed.
