### ISSUE TITLE
Confirmation E-Mail link rendering

### ISSUE THREAD

**Issue by Lord-Brett-Sinclair** [in2code-de/femanager#308]
Hi there, 
maybe someone can help me out.
Somehow the domain is missing in both links (confirm, reject) that are sent via email to the user. 

instead: http://foobar.org/register/?tx_femanager_pi1%5Baction%5D=confirmCreateRequest....
this appears: register/?tx_femanager_pi1%5Baction%5D=confirmCreateRequest....

It's just that the domain is missing, if I copy the link and add the domain manually, the confirmation process works well.

Thanks a lot for your suggestions und help!

**Comment by sbusemann** [comment]
are you using TYPO3 V9 oder V10?

Do you have a full domain in your site config?

**Comment by Lord-Brett-Sinclair** [comment]
Sorry I should have mentioned that. I'm using typo3 v10.

Yes, the domain in template/setup is like http://subdomain.domain.org/ - the URL rendering works fine on all pages.
