### ISSUE TITLE
Event dispatching not documented

### ISSUE THREAD

**Issue by luberti** [in2code-de/femanager#309]
Hello, I'have noticed that documentation of version stille refers to signal slots available, while you have moved to the event dispatch intterfaces

**Comment by MaxGTR** [comment]
Furthermore EventDispatcher seems to not working, any events from femanager appear in the backend (Configuration > Event Listeners).

**Comment by davdenic** [comment]
Are any updates on this?
Thanks

**Comment by neufeind** [comment]
For an example how to work with events see #445 (sorry, didn't see this ticket here before).
