### ISSUE TITLE
Missing validation at date_of_birth field throws MySQL exception "out of range"

### ISSUE THREAD

**Issue by Moongazer** [in2code-de/femanager#310]
If a user enters e.g. 12/12/1212 into the `date_of_birth` form field, the following exception is thrown:
```
(1/3) #1470230766 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException

Out of range value for column 'date_of_birth' at row 1
```

Sure, its a fake value, but still the validation needs to take care of that imo. I tried to fix it by adding a range in the `fe_users.php` TCA config:
```
            'range' => [
                'lower' => mktime(0,0,0, 1, 1, 1900)
                'upper' => mktime(0, 0, 0, 12, 31, 2039),
            ]
```
But eval is `date` and the range works only on `int` it guess, so not sure what can be an easy fix here (as it is kind-of a core/TCA problem...)

**Comment by spoonerWeb** [comment]
@Moongazer If you need such dates, you can easily just change the `date_of_birth` field to a `BIGINT(20)`.

Add this to an `ext_tables.sql` file in your sitepackage:

```sql
CREATE TABLE fe_users (
    date_of_birth BIGINT(20) DEFAULT 0 NOT NULL
);
```

**Comment by Moongazer** [comment]
True, could be a acceptable workaround, thanks
