### ISSUE TITLE
No Attachments on Invitation Email

### ISSUE THREAD

**Issue by dasoe** [in2code-de/femanager#311]
Dear all,
**thanks for this great Extension!**

At the moment I have a problem I am stuck with. I am trying to send Invitation email with an attachment I set in Typoscript (plugin.tx_femanager.settings.invitation.email.invitation.attachments.10 = TEXT...). Mail ist sent fine, I can access the file in Frontend (it is a pdf), but no attachment is added to the mail. So I debugged SendMailService:
- it is triggered
- the file path is correctly passed on from Typoscript
- $email->attachFromPath($file); is called
- I can overwrite subject in the function, so mail object is accessible
Still I did not manage to get an attachment. Also tried different paths of course (absolute, relative and the like). 
I would be very happy for any hint or experience.
Typo3 is 10.4.9. femanager is 6.1.1.

Thanks for any hint!
oe

**Comment by christophlehmann** [comment]
I can confirm the issue. 

The example in the [Docs](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Mail/Index.html#send-email-with-mailmessage) works so far...
