### ISSUE TITLE
Call to a member function findAllForFrontendSelection() on null

### ISSUE THREAD

**Issue by grischpel** [in2code-de/femanager#314]
I hope, its not a mistake from me, but i updated femanager from TER and since then i have this Error:

![image](https://user-images.githubusercontent.com/35844133/102268723-f448a300-3f1b-11eb-94db-bcead3878005.png)

**Comment by Patta** [comment]
I can confirm for version 6.1.2 with TYPO3 10.4.12 and composer mode.

**Comment by Patta** [comment]
#245

**Comment by Patta** [comment]
PR #254 and #255 seems to fix this issue.

**Comment by grischpel** [comment]
I changed the Injections in AbstractController and ViewHelpers like this:

` /**
   * @var UserGroupRepository
   */
  protected $userGroupRepository;

  /**
   * Inject the UserGroupRepository
   *
   * @param UserGroupRepository $userGroupRepository
   */
  public function injectUserGroupRepository(UserGroupRepository $userGroupRepository) {
    $this->userGroupRepository = $userGroupRepository;
  }`

And Now it works for me... 
Only the extending in my own extension doesnt work for now, but this is an other issue

**Comment by sbusemann** [comment]
resolved in develop
