### ISSUE TITLE
Double activation email when confirmation by user is active.

### ISSUE THREAD

**Issue by hgs5admin** [in2code-de/femanager#317]
If confirmation by user and confirmation by admin is activated, the email is sent to the admin twice, once directly after filling out the form and then when the user has confirmed.

In my opinion, the e-mail after the user's confirmation would be sufficient.

**Comment by NiciKreuz** [comment]
@hgs5admin please set the createAdminNotify like below:

`plugin.tx_femanager.settings.new.email.createAdminNotify._enable.value = 0`

then your problem is fix.
