### ISSUE TITLE
Module configPID overwrite not working

### ISSUE THREAD

**Issue by Patta** [in2code-de/femanager#318]
TYPO3 10.4.12
femanager 6.1.2
Composer mode
PHP 7.4.13

The configuration of the pid with the typoscript main template storage like explained [here](https://docs.typo3.org/p/in2code/femanager/master/en-us/Upgrade/Index.html#to-version-6-0-0) is not working.

I added `module.tx_femanager.settings.configPID = 1084` to PageTS and/or UserTS, but i get always a PageNotFoundException.

`[CRITICAL] request="ec4d08534fff4" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1343589451: Could not fetch page data for uid 1. | TYPO3\CMS\Core\Exception\Page\PageNotFoundException thrown in file REMOVED\private\typo3\sysext\core\Classes\Utility\RootlineUtility.php in line 258. Requested URL: REMOVED.localhost/typo3/index.php?route=%2Fmodule%2Fweb%2FFemanagerM1&token=--AnonymizedToken--&id=11029 - {"TYPO3_MODE":"BE","exception":"TYPO3\\CMS\\Core\\Exception\\Page\\PageNotFoundException: Could not fetch page data for uid 1.`

It seems like the default configPID 1 is still used.

Note: The folder with the user records is placed outside of the site page tree. Nevertheless, this error happens on every page with the femanager module.

**Comment by Patta** [comment]
Workaround: added ext_typoscript_setup.txt to sitepackage to overwrite the femanager backend module configPID.

**Comment by Patta** [comment]
#360 does not fix this in version 6.3.0. same error. same workaround.

**Comment by netfeld** [comment]
I added `module.tx_femanager.settings.configPID = 2` to my root template (pid=2) and everything works fine.

**Comment by Patta** [comment]
@sbusemann neither in the root typoscript template, nor in the as documented pagets it works. In my case it can't work in the root typoscript template either, because the backend module is opened on a user folder, which is placed outside the page tree. My workaround from above still works.

```
Userfolder
---
Site
- Page 1
- Page 2
- ...
```

**Comment by sbusemann** [comment]
I added a note in the documentation
