### ISSUE TITLE
femanager executes twice

### ISSUE THREAD

**Issue by SilkeDX** [in2code-de/femanager#324]
I'm using femanager 5.4.2 on TYPO3 8.7.32. I have two languages, DE and EN. When I register and confirm a user in German, I first get the message (via flash messages) that the profile is confirmed (in German) and after that a message, that the profile is already confirmed (in English). I also get some emails double, one in German, another one in English for example after the admin has confirmed the user.

**Comment by sbusemann** [comment]
I can not reproduce this in our test development. Maybe you have a misconfiguration in your language setup
