### ISSUE TITLE
enabling non admin beuser to impersonate feuser doesn't work

### ISSUE THREAD

**Issue by Nostrabramus** [in2code-de/femanager#330]
I tried to add in user tsconfig this line:
`tx_femanager.UserBackend.enableLoginAs = 1`
to allow a non admin beuser to impersonate feuser
it works in list view and show the button but if I try to use it I receive an exeption 
` 
(1/1) Error
Call to a member function getTSConfig() on null

    public static function isAdminAuthentication()
    {
        $userAuthentication = self::getBackendUserAuthentication();

        return $userAuthentication->user['admin'] === 1 || (int)$userAuthentication->getTSConfig()['tx_femanager.']['UserBackend.']['enableLoginAs'] === 1;

 }
`
debugging the code it seems that the problem is that $userAuthentication is null

can you help me?

kind regards

**Comment by Nostrabramus** [comment]
I noticed that using femanager 5.4.2 and TYPO3 9.5.13 it works

I had found the problem on femanager 6.1.1 and TYPO3 10.4.11

**Comment by spoonerWeb** [comment]
Working in current `develop` branch.
