### ISSUE TITLE
New gender type

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/femanager#334]
Actually there is only male and female as option for the field gender. A third option (various, german: divers) would be great. Thank you!

**Comment by grosswerner** [comment]
According to experts, the Federal Constitutional Court's decision that people have the right to a third gender entry could result in an obligation for store operators to offer a third gender for selection in addition to the salutation "Ms." and "Mr.".

**Comment by sbusemann** [comment]
duplicate of #150
