### ISSUE TITLE
Override UserBackend Templates

### ISSUE THREAD

**Issue by bh-teufels** [in2code-de/femanager#336]
is it possible to overrides the UserBackend Templates?

state is in table headline but not in data so the anger is wrong and full name not working
so i want to fix that and maybe use additional fields.

![Bildschirmfoto 2021-02-18 um 18 48 26](https://user-images.githubusercontent.com/38100744/108399315-43f86300-721a-11eb-8bf3-5c0e314d4ed8.png)

**Comment by spoonerWeb** [comment]
Overriding could be fixed by #360.
