### ISSUE TITLE
configPID

### ISSUE THREAD

**Issue by gamma-2017** [in2code-de/femanager#342]
Hi,
I tried to use the setting described under "to version 6.0.0" at <https://docs.typo3.org/p/in2code/femanager/master/en-us/Upgrade/Index.html>. However, in my present typo3 setup, there is nothing at PID=1 and I need that to be 5. I am not an experienced typo3 user, so maybe I did not really find the correct solution. Still:

(1).

I had to change that number in the file EXT:femanager/ext_typoscript_setup.txt to make the backend work properly.

(2)

The text does not say what configPID points to. It is *not* the feuser folder. It is the page containing the typoscript that contains all the configs including the pointer storagePID to the feuser folder.

**Comment by Patta** [comment]
#318
