### ISSUE TITLE
Exception when register user with image

### ISSUE THREAD

**Issue by nhovratov** [in2code-de/femanager#343]
In SendMailService on line 138: $email->embedFromPath($image) the return value is the Mailmessage instance rather than the embedded image (unlike in old SwiftMail). This causes an exception as the UserProperties Partial tries to cast the object to a string.

**Comment by nhovratov** [comment]
![Screenshot_2021-03-24 TYPO3 Exception](https://user-images.githubusercontent.com/19343425/112352682-42173900-8ccb-11eb-839b-c16e1fc528a6.png)

**Comment by spoonerWeb** [comment]
Confirmed.

**Comment by sbusemann** [comment]
solved by https://github.com/in2code-de/femanager/pull/393
