### ISSUE TITLE
Override Email Templates not wroking

### ISSUE THREAD

**Issue by bh-teufels** [in2code-de/femanager#344]
i tried to override the Email Templates
for this i made a override EXT with TS Setup it is working for everything except Templates/Email and Templates/UserBackend

my TS Setup:
```
plugin.tx_femanager {
	view {
		templateRootPaths {
			0 = EXT:femanager/Resources/Private/Templates/
			1 = {$plugin.tx_femanager.view.templateRootPath}
			2  = EXT:my_ovr_femanager/Resources/Private/Templates/
		}
		partialRootPaths {
			0 = EXT:femanager/Resources/Private/Partials/
			1 = {$plugin.tx_femanager.view.partialRootPath}
			2  = EXT:my_ovr_femanager/Resources/Private/Partials/
		}
		layoutRootPaths {
			0 = EXT:femanager/Resources/Private/Layouts/
			1 = {$plugin.tx_femanager.view.layoutRootPath}
			2  = EXT:my_ovr_femanager/Resources/Private/Layouts/
		}
	}
}
```

**Comment by bh-teufels** [comment]
seems that In2code\Femanager\Utility\TemplateUtility -> getTemplateFolders
call of $configuration not working -> select all Configuration not only of EXT

so $configuration['view'] always empty

$configuration = self::getConfigurationManager()
            ->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK, 'femanager');
$configurationManager->getConfiguration(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
$storagePid = $extbaseFrameworkConfiguration['plugin.']['tx_guesthouse_guesthouse.']['settings.']['storagePid'];

**Comment by enem-frir** [comment]
I have the same issue, unfortunately I'm not that deep into extension writing (php).

How did you solve the issue? 
Did you change the configuration in Template Utility.php? And if so, which lines did you change and to what?

Thanks in advance! You would help me a lot.

**Comment by bh-teufels** [comment]
i think that must be fixed from Extension Developer.

i made a copy of the Extension and used that instead so i could change the Templates directly in the copy.
to get the overwrite working the getTemplateFolders - Function needed to be adjusted bit i haven't got around to do this this yet.

**Comment by sbusemann** [comment]
Overwriting works:
![bild 1](https://user-images.githubusercontent.com/3660954/121781847-f926a080-cba6-11eb-8e66-4f0ab453f99e.png)

This was my test config:
plugin.tx_femanager.view.templateRootPaths.2 = fileadmin/femanager/Templates/

**Comment by bh-teufels** [comment]
i have this config in (SETUP)

plugin.tx_femanager.view.templateRootPaths.99 = EXT:my_thm/Resources/Private/Overrides/femanager/Templates/

but not working for Invitation.html Template 
Path of my Template: /ext/my_thm/Resources/Private/Overrides/femanager/Templates/Email/Invitation.html
