### ISSUE TITLE
Set errorClass in Form-Fields

### ISSUE THREAD

**Issue by ha75** [in2code-de/femanager#346]
How to set an error class to any form field if it is not valid?
I tried to add `errorClass` e.g. in Partials/Fields/Username.html
```
<femanager:form.textfield
		id="femanager_field_username"
		property="username"
		class="form-control"
		errorClass="form-control"
		additionalAttributes="{femanager:Validation.FormValidationData(settings:settings,fieldName:'username')}" />
```
However, this is not working.

**Comment by spoonerWeb** [comment]
I can confirm this. Neither with client validation (JS writes `error` as class) nor server validation (no class was added).
