### ISSUE TITLE
Backend module TypeError from RatelimiterService

### ISSUE THREAD

**Issue by Patta** [in2code-de/femanager#348]
TYPO3 10.4.16
PHP 7.4.19
femanager 6.2.0
composer mode

Error with femanager backend module on any page or folder since version 6.2.0.

`[CRITICAL] request="87fe0eb5dc27a" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of In2code\Femanager\Domain\Service\RatelimiterService::getTSFE() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned | TypeError thrown in file /var/www/vhosts/REMOVED/private/typo3conf/ext/femanager/Classes/Domain/Service/RatelimiterService.php in line 41. Requested URL: https://REMOVED/typo3/index.php?route=%2Fmodule%2Fweb%2FFemanagerM1&token=--AnonymizedToken-- - {"TYPO3_MODE":"BE","exception":{}}`

**Comment by bh-teufels** [comment]
i get the same error on
Typo3 10.4.22
PHP 7.4.25
femanager 6.3.2

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of In2code\Femanager\Domain\Service\RatelimiterService::getTSFE() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned | TypeError thrown in file [...]/web/typo3conf/ext/femanager/Classes/Domain/Service/RatelimiterService.php in line 41.`
