### ISSUE TITLE
"Table 'typo3.cache_femanager_ratelimiter' doesn't exist" error after upgrading to 6.2.0

### ISSUE THREAD

**Issue by agoradesign** [in2code-de/femanager#362]
After updating to 6.2.0 (from 6.1.2) we ran into the problem with the missing FE controller, that was fixed here: https://github.com/in2code-de/femanager/commit/61d4c250c8ad5ba33e1010fdba520eeb084165f8

We have then switched temporarily to dev-develop version, in order to get the bugfix in. Now we have still the problem that the cache table is missing. Could that be that the broken 6.2 release did not complete a database update script?

`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'TRUNCATE `cache_femanager_ratelimiter`': Table 'typo3.cache_femanager_ratelimiter' doesn't exist | Doctrine\DBAL\Exception\TableNotFoundException thrown in file \vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php in line 46. Requested URL: /typo3/index.php?route=%%2Frecord%%2Fcommit&token=--AnonymizedToken--&cacheCmd=all
`

**Comment by spoonerWeb** [comment]
The table should be created automatically with the DB compare tool in Install Tool. 
Did you run that compare? If not, is it fixed by running it?

**Comment by Patta** [comment]
Maybe the new tables should be documented in the release notes with a hint to do a db compare after the update.

**Comment by spoonerWeb** [comment]
That's why I'm asking if it's fixed after DB compare. 👍

**Comment by agoradesign** [comment]
thank you very much! that solved the problem :)

When is a 6.2.1 release planned that includes the fix in https://github.com/in2code-de/femanager/commit/61d4c250c8ad5ba33e1010fdba520eeb084165f8 ? 6.2.0 is quite broken due to that

**Comment by mhuber84** [comment]
The same problem exists when updating from 5.4.2 to 5.5.0 and the database compare solved the problem. After the `ddev composer update` the `vendor/bin/typo3cms cache:flush` failed until I did the `vendor/bin/typo3cms database:updateschema`.
Can the bugfix be backported?
