### ISSUE TITLE
Update documentation about how to add fields

### ISSUE THREAD

**Issue by spoonerWeb** [in2code-de/femanager#367]
With v10 there came some changes:

* `config.tx_extbase.persistence` and `config.tx_extbase.objects` were deprecated in v9 and removed in v10
* Overriding the controller to set the overwritten user object not needed any more

**Comment by mhuber84** [comment]
@spoonerWeb can you have a look at my pull request, please? Is this what you meant with "Overriding the controller to set the overwritten user object not needed any more"?

**Comment by sbusemann** [comment]
resolved in develop
