### ISSUE TITLE
Field missing in multiple error messages

### ISSUE THREAD

**Issue by dahaupt** [in2code-de/femanager#368]
In our case, we enabled the validation type `mustInclude = number,letter` for the field `password`.

Error message in registration form (e.g. in case of a password without a number):  

![grafik](https://user-images.githubusercontent.com/15915048/122753235-3ddec580-d292-11eb-949b-d5bd726b4f1b.png)

The field is missing in the output, because the error code is `0` because the actual `$fieldName` is casted to an integer in extbase.

There was already a fix for this, which unfortunately does not cover every validation type: 3059f81.

**Comment by spoonerWeb** [comment]
Would that be fixed by this PR? https://github.com/in2code-de/femanager/pull/304

**Comment by dahaupt** [comment]
@spoonerWeb Yes! But the PR fixes another issue I am not aware of, yet.

I was not aware of this PR and created my own, which only fixes this issue (#369).
