### ISSUE TITLE
Re-Send Double Opt-in Mail

### ISSUE THREAD

**Issue by moger-xx** [in2code-de/femanager#37]
Sometimes the double opt in mails are regarded as spam. Then the account record was created but is in an unconfirmed state. Currently there is no way to get out of this state since the user cannot delete his account nor can he trigger resending the confirmation mail.

Thus, it would be very handy if the extension could offer a functionality to re-send a confirmation mail. An option to disable this functionality might be handy to address legal concerns.

**Comment by einpraegsam** [comment]
Nice idea but not planned at the moment.

**Comment by moger-xx** [comment]
Closed as in "I don't want that feature" or closed as in "I don't have time"? Thinking about a PR.

**Comment by einpraegsam** [comment]
We're short before 4.0.0 release and will focus on that. Nevertheless PR are always welcome.

**Comment by sbusemann** [comment]
Hi @moger-xx - this could be an idea for the BE Module (Frontend Users). We could add a new button to all pending registrations and try to resend it. Could that be a solution?

**Comment by sbusemann** [comment]
But what happens, if the user closed the last view? Then we can't start the process again.

**Comment by moger-xx** [comment]
This should be covered by case number 3. We could link to a view containing a form, in which the user can enter the e-mail-adress (username) again and trigger the re-sending. of course the same restrictions apply as in case number 2. Think of it being somewhat like a password forgot functionality.

**Comment by sbusemann** [comment]
I try to summarize:
* We need an action, that enables a fe_user or and be_user to resend an open request (Double Opt-in E-Mail)
* We need an option for the Plugin, that an editor is able to decide, wether this option is shown or not, at view, after the first step of the registration is done
* We need an additional view ( Re-send Double Opt-in E-Mail), that an user is able to start this action and / or an detection during the regular registration, if this user exists. 

Did I miss anything?

**Comment by moger-xx** [comment]
Sounds good :-)

**Comment by sbusemann** [comment]
@moger-xx can you send your contact data to stefan.busemann(at)in2code.de  - then i can create an offer.

**Comment by sbusemann** [comment]
is released in 4.2.0

**Comment by moger-xx** [comment]
Also, the search form in the backend view "listOpenUserConfirmations" posts against the wrong action ("confirmation" instead of "listOpenUserConfirmations"), so search is not possible.
