### ISSUE TITLE
BUG when editing profile

### ISSUE THREAD

**Issue by HenryAveMedi** [in2code-de/femanager#376]
Am I missing something? since last update i'm getting the following error when I test editing an FE user profile in FE:

Oops, an error occurred!
Argument 2 passed to In2code\Femanager\Utility\FrontendUtility::forceValues() must be of the type array, null given, called in /…/typo3conf/ext/femanager/Classes/Controller/EditController.php on line 63

I have own templates, deactivated them all, and I still get the same error with the default templates of the extension

TYPO3 10.4.15
femanager 6.3.0

**Comment by sbusemann** [comment]
can you post your TypoScript Config of the area "edit"

**Comment by HenryAveMedi** [comment]
```
plugin.tx_femanager.settings {
  new.forceValues {
    beforeAnyConfirmation {
    # Usergroups can be set with a commaseparated list
      usergroup = TEXT
      usergroup.value = 1
    # Set a fix value
      # email = TEXT
      # email.value = service@in2code.de
    }
    # Overwrite on user confirmation (only if user confirmation was activated)
    onUserConfirmation {
    # Usergroups can be set with a commaseparated list
      usergroup = TEXT
      usergroup.value = 1
    # Set a fix value
      # company = TEXT
      # company.value = in2code.de
    }
    # Overwrite on admin confirmation (only if admin confirmation was activated)
    onAdminConfirmation {
    # Usergroups can be set with a commaseparated list
      usergroup = TEXT
      usergroup.value = 1
    # Set a fix value
      # www = TEXT
      # www.value = http://www.in2code.de
    }
  }
  edit {
    forceValues < new.forceValues
  }
}
```

**Comment by HenryAveMedi** [comment]
yep, my bad, somehow it used to work with that configuration till now, but it actually needed to be

`edit.forceValues < plugin.tx_femanager.settings.new.forceValues`
