### ISSUE TITLE
uniqueInDb does not respect endtime

### ISSUE THREAD

**Issue by okrgb** [in2code-de/femanager#382]
In the case of a trial-subscription with an expired trial phase (endtime ist set) multiple trial-subscriptions with the same username are possible even when "uniqueInDb = 1" is set via validation.

Registration 1: 
	"username = registration@femanager.com" has setting "endtime = 18.07.2021 00:00:00" (= already expired)
Registration 2: 
	"username = registration@femanager.com" is possible to register allthough "new.validation.username.uniqueInDb = 1" is set

What am I doing wrong?

**Comment by sbusemann** [comment]
@okrgb uniqueInDb checks only "active" user with the state "deleted=0". We could add an additional validation, which could cover your case. If you are interested, you can ask for an offer.

**Comment by okrgb** [comment]
@sbusemann Thank you for your reply! 
Although I find the naming of the option "uniqueInDb" kind of misleading if neither hidden nor deactivated users are taken into account, I am interested in implementing an additional validation if this differs from the following bugfix from version 6.2.0 of 06.06.2021 - [BUGFIX] Validation for checkUniqueDb ignores starttime/endtime - thx to in2code
