### ISSUE TITLE
femanager 5.5.1 does not support PHP 7.4

### ISSUE THREAD

**Issue by griesi007** [in2code-de/femanager#388]
Typo3 9 LTS supports PHP 7.4. femanager 5.5.1 cannot be installed on PHP 7.4 (at least not with the Extension [Manager)]
![Uploading 16-08-_2021_10-02-31.jpg…]()
 as  ext_emconf.php limits compatibility to 'php' => '7.0.0-7.3.99', femanger should be compatible to the system requirements of Typo3 9 LTS

**Comment by spoonerWeb** [comment]
You mean 5.5.1?

**Comment by griesi007** [comment]
Yes soryy for the typo: 5.5.1

**Comment by TehTux** [comment]
FYI: PHP 7.0 does not work either:
htdocs/typo3conf/ext/femanager/Classes/DataProvider/CountryZonesDataProvider.php
Line: 65
Nullables is only allowed since PHP 7.1

**Comment by sbusemann** [comment]
I do not have a proper enviroment for the 5.5 Branch. So I will do the simplest way: Remove support for PHP 7.0 and still do not support 7.4.

If someone likes to sponsor the testing time, i can support it. For version 6 (and future versions) the testing process is now simple via GitHub actions.
