### ISSUE TITLE
Bug with email subject in ->finalCreate() ?

### ISSUE THREAD

**Issue by koehnlein** [in2code-de/femanager#397]
I had a problem with sending the creation mail, which already was solved in #391

But while debugging and searching the problem, I found the same code with `['subject']['data']` on two other places:

https://github.com/in2code-de/femanager/blob/98d552835dc8419ae8a99b95b5b56f8bfe33f8cd/Classes/Controller/AbstractController.php#L253
https://github.com/in2code-de/femanager/blob/98d552835dc8419ae8a99b95b5b56f8bfe33f8cd/Classes/Controller/AbstractController.php#L268

Would that be worth a merge request or is everything ok with this code there?

**Comment by sbusemann** [comment]
thanks @koehnlein for hint, but this is not an issue. At this lines, in the TS an xlf file is used, which still works.
