### ISSUE TITLE
Expected response code "250" but got code "550", with message "550 "envelope sender not allowed"

### ISSUE THREAD

**Issue by grosswerner** [in2code-de/femanager#404]
Hello,

first of all, my configuration:

Website-provider is Domainfactory
Typo3 is Version 10.4.21
Femananger Version 6.3.2

My global mail settings are as following:

[MAIL][transport] = smtp 
[MAIL][transport_smtp_server] = smtprelaypool.ispgateway.de:465 
[MAIL][transport_smtp_encrypt] = true 
[MAIL][transport_smtp_username] = w.gross@kochwerker-tuete.com 
[MAIL][transport_smtp_password] = ***********

/**************************************************
tx_femanager 
**************************************************/
plugin.tx_femanager {
        settings.new {

                email.createUserConfirmation._enable.value = 1
                email.createAdminConfirmation._enable.value = 1
                email.createUserNotify._enable.value = 0
                email.createAdminNotify._enable.value = 0
                
                fillEmailWithUsername = 1
         
                validation {
                        # Enable clientside Formvalidation (JavaScript)
                        _enable.client = 1

                        # Enable serverside Formvalidation (PHP)
                        _enable.server = 1

                        company {
                                required = 1
                        }

                        email {
                                required = 0
                        }    
                        username {
                                required = 1
                                email = 1
                                uniqueInDb = 1
                        }
                }
        }
}

I have integrated the plugin "femanager" on the page https://www.kochwerker-tuete.com/benutzer/registieren-als-metzger where new user should start their registration process. When I now fill out the form I get the following message via my mail account

-----------------------------------

Hello w.f.gross@t-online.de,

Please confirm your registration on our server by clicking on the link below:
Confirm Profile

If your profile was mistakenly registered on our system, you can delete it by clicking on the following link.
Delete profile

Your Kochwerker Team.

-----------------------------

Now when I try to confirm my profile with clicking on "Confirm Profile" I get the following error message from the debuger:

(1/1) #550 Symfony\Component\Mailer\Exception\TransportException.
Expected response code "250" but got code "550", with message "550 "envelope sender not allowed w.f.gross@t-online.de".

The "t-online.de" mail adress is the one i have registered my test user with.

I know that I can't send mails from my SMTP account that contains a "foreign sender", but where and how do I set this in the femanager so that I don't get this error message anymore?

If I set email.createAdminConfirmation._enable.value to 0 the error is gone, but the admin does not get a mail notification that the user has confirmed his login/email which I, as admin, would like to receive.

With kind regards
Werner Groß

**Comment by sbusemann** [comment]
Most probably this is a SPF violation. Please take care, that you setup a proper sender Adress and that you do not send out mails in the name of the sender.
