### ISSUE TITLE
Terms field missing

### ISSUE THREAD

**Issue by dennismetz** [in2code-de/femanager#405]
The "Terms" field is missing in the FlexForm. The corresponding template also refers to a variable (settings.misc.termsUrl) that is not defined in TypoScript.

**Comment by spoonerWeb** [comment]
I have the "Terms" field in the FlexForm for Registration, see:

<img width="606" alt="grafik" src="https://user-images.githubusercontent.com/1793083/148042383-1006cd0b-6848-40b2-a7ad-d0f4be87215e.png">

**Comment by sbusemann** [comment]
No feedback given - so I close this issue
