### ISSUE TITLE
missing labels in fe user tab "Benutzer Registrierung"

### ISSUE THREAD

**Issue by medarob** [in2code-de/femanager#409]
It seems that there are some labels missing in the FE User

![grafik](https://user-images.githubusercontent.com/33951787/143906831-af25ed8e-87ac-4203-b738-e5e7ff676d9b.png)

TYPO3 10.4.21
femanager: 6.3.2

**Comment by sbusemann** [comment]
Please update your "Manage Language Packs" -> the labels are avaialable generall
![bild](https://user-images.githubusercontent.com/3660954/144389423-a1795d5d-3a22-421a-b31b-e7ef46b8d59f.png)
y.
