### ISSUE TITLE
is it possible to move ext_typoscript_setup.typoscript ?

### ISSUE THREAD

**Issue by davdenic** [in2code-de/femanager#420]
Hi there, 
is it possible to move ext_typoscript_setup.typoscript to Configuration/Typoscript/Backend/setup.typoscript ?
Otherwise I cannot ovverride the typoscript which is written in that file.

**Comment by sbusemann** [comment]
no this is not intended, to ensure, that the extension works.

You can override everything in your installation via typoscript.

To delete a setting f.e., you can use:
module.tx_femanager >

see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.html#object-unsetting-the-sign
