### ISSUE TITLE
rendering country field fails on check for static_info_tables condition

### ISSUE THREAD

**Issue by maikusch** [in2code-de/femanager#422]
i use the country field for registration, but without static_info_tables.
that uses the internal section in country.html field template.
But there is an error in frontend, that the class CountryRepository from static_info_tables is does not exist.
Sure, because static_info_tables is not installed.
i saw there is a check if static_info_tables is installed in the abstractController. This condition returns false.
so i think, nothing from static_info_tables should be loaded or requested
So how can i fix this error? (bearbeitet)

after that, i removed the section which should be rendered if static_info_Tables is installed, and everything runs fine.

**Comment by sbusemann** [comment]
Which version do you use?
(I will reopen this issue after getting feedback)
