### ISSUE TITLE
Invalid value "LANGUAGE" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType"

### ISSUE THREAD

**Issue by martinwolfdd** [in2code-de/femanager#423]
Hello, 

in my Installation I see this Error when I start FEMANAGER in Frontend and Backend. It is a German Installation. Thank you for your help.

Martin

Oops, an error occurred!
Invalid value "LANGUAGE" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType"

More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1381512761).

Error cames in TYPO3 Version 10.4.22

**Comment by sbusemann** [comment]
Die you extend the Femanager? 

It seems not for a general problem with the femanger.

**Comment by sbusemann** [comment]
no feedback received
