### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by pietvb93** [in2code-de/femanager#433]
Hi,

have you planned to support PHP 8?
Do you have a timeline in mind?

Thanks, Piet

**Comment by pietvb93** [comment]
thanks. are you aware of rector to upgrade the code to php 8 automatically?
https://github.com/rectorphp/rector
Please tell me if I can contribute.

**Comment by sbusemann** [comment]
I am aware of rector :-) 

Support for PHP 8 will cause mainly testing effort to avoid empty keys in arrays. Of course - help is always welcomed.

**Comment by pietvb93** [comment]
Hi, I would be happy to support testing and issue analysis. Is there already a release available for testing?

**Comment by sbusemann** [comment]
no not yet. We will start in ~two weeks
