### ISSUE TITLE
PHP ^8.0 support

### ISSUE THREAD

**Issue by mediaessenz** [in2code-de/femanager#435]
The current version 7.0.0 of femanager is compatible to TYPO3 11, but not to the php versions this release supports (7.4-8.1).
 
The problem is that support for php 7.4 will expire in less than 4 months.

Because this, a php 8 compatible version would be a great thing.

**Comment by sbusemann** [comment]
this is WIP as part of https://github.com/in2code-de/femanager#early-access-programm-eap

**Comment by sbusemann** [comment]
femanager 7.1 is now available with support for PHP 8.0 and 8.1 as part of our Early Access Programm - Please use this branch (https://github.com/in2code-pro/femanager/tree/pro) until the public release.

Public Release will be in November.

**Comment by MacGyer** [comment]
Hello guys,

is there a specific release date set for femanager which is compatible to PHP 8?

Thanks for getting back.

**Comment by fsnd-tech** [comment]
Hello @sbusemann 
the link to the branch that supports PHP 8.x is not longer valid.
Is there a release date for a version of femanager for PHP 8.
We are currently moving several projects to TYPO3 11.x and PHP 8.x
Thanks

**Comment by sbusemann** [comment]
Support for PHP 8 is available via https://www.in2code.de/en/agency/typo3-extensions/early-access-program/ 

The public release is Expected end of November / Beginning of December

**Comment by fsnd-tech** [comment]
Thanks @sbusemann

**Comment by tchsupport** [comment]
> Support for PHP 8 is available via https://www.in2code.de/en/agency/typo3-extensions/early-access-program/
> 
> The public release is Expected end of November / Beginning of December

when :)?

**Comment by NoHow81** [comment]
> Support for PHP 8 is available via https://www.in2code.de/en/agency/typo3-extensions/early-access-program/
> 
> The public release is Expected end of November / Beginning of December

January 2023 is here, when will the update be published?

**Comment by sbusemann** [comment]
It will be released, when all issues are solved. This was today. The code is available in the publich development branch and will get a release next week.
