### ISSUE TITLE
Confirmation via Confirmation view is not working

### ISSUE THREAD

**Issue by Cleee** [in2code-de/femanager#448]
Typo3 11.5.9
femanager 7.0.0
PHP7.4

The User Confirmation using the Confirmation View is not working in this environment:

(1/1) Error
Class 'In2code\Femanager\Controller\RequestFactory' not found

![2022-09-29_11h25_55](https://user-images.githubusercontent.com/42375095/192994707-53ad09f5-7ee9-4245-8952-11c62355ed75.png)

**Comment by peerlight** [comment]
same here

TYPO3 11.5.16
PHP-Version 7.4.30
femanager 7.0.0
composer installation

**Comment by Cleee** [comment]
If you have problems to reproduce this error:

If i disable the confirmation by user (settings.new.confirmByUser) the Confirmation view dont shows me any type of confirmation request. If its activated it shows me the user and the error on the screenshot occurs when i accept or decline the registration.

It would be very nice if the Confirmation view gets fixed. This is the only reason why i use femanager for fe registration tbh.

Thank you :)

**Comment by Cleee** [comment]
dasdad

**Comment by sbusemann** [comment]
Works in TYPO3 12 Version 8.
