### ISSUE TITLE
"login as" not working if root page is shortcut

### ISSUE THREAD

**Issue by cehret** [in2code-de/femanager#454]
Hello,

the link in backend for "login as" is rendered like 
`/?type=1548943013&tx_femanager_pi1[user]=`

In my installation the user is not logged in. As far as I could see this happens because my root page is a shortcut to first subpage of selected/current page.
I could fix the "login as" feature by changing the rendered link to:
`/index.php?id=296&type=1548943013&tx_femanager_pi1[user]=`
(296 is the page with the login form)

I would like to find a "permanent" solution for this issue because if I change the backend template in the extension this change is overridden with the next femanager update. So is there any possibility to override the template with an own extension (like it is possible with the frontend templates) or is there any other possibility to get this feature working?

Thank you

Christian

**Comment by sbusemann** [comment]
we plan to use a middleware instead
