### ISSUE TITLE
Server-side validation of image field always fails

### ISSUE THREAD

**Issue by sns-ck** [in2code-de/femanager#459]
After upgrading from version 7.0.0 to 7.0.1 the server-side validation changed and since then the validation of the image uploaded in the registration form always fails if it has been declared as a required field because the Uid doesn't exist at this point (only the uidLocal) and $object->getUid() returns null. The condition`if ($object instanceof FileReference) {
                    return true;
                }` is probably missing here

`public/typo3conf/ext/femanager/Classes/Domain/Validator/ServersideValidator.php:315`
TYPO3 Version: 11.5.5

<img width="647" alt="image" src="https://user-images.githubusercontent.com/121035403/208443043-e4f87e52-35fd-4064-be0f-190c039033db.png">

**Comment by praktikum-in2code-de** [comment]
Dear @sns-ck,
Thanks for your report. I can confirm your issue and we will try to solve the issue.

**Comment by sbusemann** [comment]
Fixed in Early Access Programm - will be released in the next public release.
