### ISSUE TITLE
femanager 2.6 Typo3 7.6 error after create - sendmail

### ISSUE THREAD

**Issue by j-lang** [in2code-de/femanager#46]
In a typo3 7.6 configuration (t3bootstrap.de) the create user form fails after pressing submit with the following error: 
```
Uncaught TYPO3 Exception
Call to a member function start() on null 

Error thrown in file
/html/typo3/typo3conf/ext/femanager/Classes/Domain/Service/SendMailService.php in line 82.
```
Debug output shows that `$this->cObj = $this->configurationManager->getContentObject();`  is null. 

The create/registration works with femanager 4.0.1 works, but there would be no typo3 7 compatibility.
There are other typo3 8 incompatible extensions, that does not allow an update to 8.6.

**Comment by einpraegsam** [comment]
Hi, I never heard about this problem - maybe it's related to another extension (t3bootstrap or so). But femanager 2.6 is not supported any more.
