### ISSUE TITLE
UserConfirmation mail link not working

### ISSUE THREAD

**Issue by alexingo** [in2code-de/femanager#464]
Hi,

I've updated to femanager 7.1.0 with Typo3 11.5.22, php 8.

After clicking the confirmation link in the email an url is generated with the url site.de/<a%20href="/info/newsletter/">Newsletter</a>

Deletion of user profile works ...
The femanager registration plugin is in site-id 106.
plugin.tx_femanager.settings.new.userConfirmationRedirect.typolink.parameter = 106

**Comment by praktikum-in2code-de** [comment]
Dear @alexingo,
Thanks for your report. I have tested your settings in our develop environment and can not reproduce your issue. Please check your TS settings and your HTML templates and compare it with the default settings.

**Comment by alexingo** [comment]
After adjusting plugin.tx_femanager.settings.new.userConfirmationRedirect it works - thank's a lot!
