### ISSUE TITLE
help needed with ajax validation

### ISSUE THREAD

**Issue by AntonMezger** [in2code-de/femanager#466]
Hi,

I am using typo3 9.5.0 with IIS on Windows and php 7.4.26. femanager 5.5.3 is installed and it is possible to create an user. However validation does not work, while it seems that ajax gives a problem. the console in the browser development tools tells:
 👍 
![image](https://user-images.githubusercontent.com/12997672/218045710-313503ac-2043-440f-815f-afd9c12f743e.png)

and the fetch/xhr output tells:
 👍 
![image](https://user-images.githubusercontent.com/12997672/218046193-4fd32b54-873b-4c9c-8b0b-2e2b86e4813a.png)

so I have an infinite redirect

Could you tell what is going wrong?

best regards

P.S

the page is addressed by: http://localhost/sdgzielv9/de/femanager/create

**Comment by sbusemann** [comment]
I can not test with IIS.

In my test environment the validation works. 

In the error message config.baseURL is mentioned. Please try to set it.

**Comment by AntonMezger** [comment]
I have the same problem with apache. I use the multi language feature of typo3 with slugs. Perhaps that is the reason. However perhaps could you provide me with your .htaccess file

Thanks in advance

**Comment by sbusemann** [comment]
There is no change for .htacess for femanger needed. 

Please try to set config.baseURL in your typoScript Setup
