### ISSUE TITLE
edit user through list view

### ISSUE THREAD

**Issue by AntonMezger** [in2code-de/femanager#468]
Hi,

as logged in superuser I would like to be able to edit an user by clicking in the list view. Is this possible ?

best regards

**Comment by sbusemann** [comment]
hi Anton, which list view do you mean? Frontend or Backend?

**Comment by AntonMezger** [comment]
Hi,

I meant in the frontend, but that could be a feature for a superuser to edit another user data. I am editing the users in the backend now.
