### ISSUE TITLE
typo3 edit error in backend

### ISSUE THREAD

**Issue by AntonMezger** [in2code-de/femanager#469]
When trying to edit a website user through the backend I get the following typo3 error:

Oops, an error occurred!
Too few arguments to function In2code\Femanager\DataProvider\CountryDataProvider::__construct(), 0 passed in C:\inetpub\wwwroot\typo3_src-9.5.0\typo3\sysext\core\Classes\Utility\GeneralUtility.php on line 3654 and exactly 1 expected

Is this a known error and can I do something about it, or is it a small bug?

**Comment by sbusemann** [comment]
Please provide the femanger and concrete TYPO3 Version

**Comment by AntonMezger** [comment]
Hi,

This error disappeared after using all means of flushing caches and deactivating and reactivating femanager

Sorry about that
