### ISSUE TITLE
Cannot set termsUrl

### ISSUE THREAD

**Issue by millemedia** [in2code-de/femanager#47]
When I set the termsUrl to a page uid, the settings.misc.termsUrl value is empty. This happens also, when I set the value in steup.txt of extension folder.

**Comment by einpraegsam** [comment]
Did you set it via FlexForm or via TypoScript?

**Comment by millemedia** [comment]
Hi Alex, I set it via TypoScript.

**Comment by einpraegsam** [comment]
Pls set it via TypoScript at the moment. There is not solution to override FlexForm Values from TypoScript. This issue is not only related to termsUrl - it's related to every setting.

**Comment by clemens7haar** [comment]
Hi all, I got the same problem with setting the termsUrl via Typoscript. Using the FlexForm works fine. Even when no FlexForm value is set, the TypoScript value is not available in the partial.
With a workaround it's now working for me. When I set the value to settings.new.misc.termsUrl and adapt the partial to use this path, the parameter is available in the template.
