### ISSUE TITLE
missing email AdminNotify after registration

### ISSUE THREAD

**Issue by metapublic-gbr** [in2code-de/femanager#472]
php 8.0
Typo3 11.5
femanager 7.1.0

since update to 7.1.0 the email to admin after successful registration will not be sent any more.

I tested this with mbox and both with and without user-confirmation

Can somebody confirm this issue?

**Comment by tieupmedia** [comment]
I can confirm this issue with flexform settings only, tested with same versions.

As I could already debug, the variable for the mail receiver from flexform is set in Line 228 in the AbstractController.php
`$createAdminNotify = ConfigurationUtility::getValue('new./notifyAdmin', $this->config);`
But $this->config doesn't contain the flexform field "new./notifyAdmin"

Workaround: Set receiver for admin notification via TS:

```
plugin.tx_femanager {
    settings {
        new {
            email {
                createAdminNotify {
                    sender {
                        email = TEXT
                        email.value = example@example.org
                        name = TEXT
                        name.value = example.org
                    }
                }
            }
        }
    }
}
```

**Comment by sns-ck** [comment]
I can confirm the error. If a notifyAdmin email is entered in the plugin as a fallback, this value cannot be read out correctly because the code has changed since 7.1.0.

In `public/typo3conf/ext/femanager/Classes/Controller/AbstractController.php:288` the call should be `$this->settings['new']['notifyAdmin']` and not `ConfigurationUtility::getValue('new./notifyAdmin' , $this->config)`.

**Comment by Patta** [comment]
I can confirm this issue. the norify email to admin after admin confirmation is not sent anymore, if the admin notify email is only set in flexform field `settings.new.notifyAdmin`.
If the email is set in typoscript `plugin.tx_femanager.settings.new.email.createAdminNotify.receiver.email.value`, the notify email to admin is sent.

TYPO3 11.5.26
femanager 7.1.1

**Comment by ic-schleyer** [comment]
I can confirm this, too
Workaround from Patta was the solution
TYPO3 11.5.30
femanager 7.2.0

**Comment by Patta** [comment]
would be great if this could be backported to v7. thanks ;)
