### ISSUE TITLE
ConfigurationUtility::getValue call with only one parameter throw exception

### ISSUE THREAD

**Issue by mediaessenz** [in2code-de/femanager#497]
Since PHP 8.1 is more restrictive a call like this throw an exception (two few arguments):

```php
ConfigurationUtility::getValue('edit/email/createUserNotify/notifyAdmin/receiver/email/value')
```
This line comes from Controller/AbstractController.php line 175, but there are some more came with version 7.1.1.

This problem can easily fixed like so:
```php
public static function getValue($key, $config = [])
{
    try {
        return $config ? ArrayUtility::getValueByPath($config, $key) : self::getDefaultConfiguration($key);
    } catch (MissingArrayPathException $ex) {
        return self::getDefaultConfiguration($key);
    }
 }
```

**Comment by mediaessenz** [comment]
... but maybe the reason for this exception is a missing `, $this->settings`

**Comment by sbusemann** [comment]
Is resolved with https://github.com/in2code-de/femanager/pull/496
