### ISSUE TITLE
TYPO3 V12 compatibility

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/femanager#498]
There will be an EXT:femanager version, which is compatible with TYPO3 core V12. It is currently under development and testing.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by linawolf** [comment]
Super, good to know!

**Comment by sbusemann** [comment]
Available via Early Access Programm - see https://www.in2code.de/en/agency/typo3-extensions/early-access-program/

Public release will be at latest end of 2023.
