### ISSUE TITLE
BE module incompatible with 404 handling

### ISSUE THREAD

**Issue by Josta** [in2code-de/femanager#50]
The user list BE module will be replaced by a 404 page for sysfolders if either of the following is the case:

- the user installed the extension "pagenotfoundhandling" or similar
- the install tool setting "[FE][pageNotFound_handling]" is set (e.g. to 1)

This is related to issue #45. Apparently just catching exceptions is not enough to detect sysfolders.

Test setup: TYPO3 8.7.9, femanager 4.1.0 from TER, (optionally) pagenotfoundhandling 2.4.5, PHP 7.1

**Comment by einpraegsam** [comment]
Yes, this may be true. The problem is a bit strange layout of your folders and pages. The error occurs because of the FE initialization in BE in https://github.com/in2code-de/femanager/blob/develop/Classes/Utility/BackendUtility.php#L120. 
I see no simple solution at the moment for this. PR are welcome of course.
Maybe @sbusemann has an idea.

**Comment by Josta** [comment]
The 404 page appears no matter whether I have the sysfolder under site_root, in another sysfolder or outside site_root. I tried this in a fresh install. So the problem is neither a strange pagetree layout nor a strange configuration (and closing the issue it seems a bit rushed).

As for the problem itself: why do we need to init TSFE in the BE module at all? As far as I can see, we only need the Typoscript configuration for the mail service.

I suggest to get the TS by extending the Extbase BackendConfigurationManager and adding this method:
```
public function getExtensionTypoScript($pageId, $extensionName, $context = 'plugin') {
	$this->currentPageId = $pageId;
        $setup = $this->getTypoScriptSetup();
	$key = $setup[$context.'.']['tx_' . str_replace('_', '', $extensionName) . '.'];
        return is_array($key) ? $this->typoScriptService->convertTypoScriptArrayToPlainArray($key) : [];
}
```

This method can then be called in BE context to retrieve the TS for the sysfolder. Alternatively, one could retrieve it for some other page where the mail service configuration is known to be stored (which the user can configure by PageTSconfig or extension extconf).

**Comment by sbusemann** [comment]
Hi @Josta thanks for the suggestion, I will check it

**Comment by AMartinNo1** [comment]
I just installed the v4.2.0 from T3 TER and receive a 404 as well.

**Comment by sbusemann** [comment]
@AMartinNo1 do you have a TS template at your page, where you call your be module? If not, you need to add a ts template with the fe manager configuration.

**Comment by wowawebdesign** [comment]
Hi, I have exact the same problem here in TYPO3 8.7.24 and femanager 4.2.5. Of course I have includes the static template of femenager on the root page of the website, I tried also to include it with an ext+ template on the sysfolder with the feuser records, but the error's still there. Do you have some tipps?

**Comment by SventB** [comment]
Same here: TYPO3 9 LTS, femanager 5.1.1
Seems to work when changing SysFolder to doktype page.
