### ISSUE TITLE
[BUG] getDirtyPropertiesFromUser() has no full support for objects

### ISSUE THREAD

**Issue by derhansen** [in2code-de/femanager#505]
The method `UserUtility::getDirtyPropertiesFromUser()` has no full support for objects. It currently only evaluates, if an object is of type `DateTime` and assumed, that all other types are `ObjectStorages`. Thus, `ObjectUtility::implodeObjectStorageOnProperty` will fail with an exception on objects, which are not of type `ObjectStorage`.

**Comment by sbusemann** [comment]
merged in develop
