### ISSUE TITLE
Validation ignores storagePid given by Plugin

### ISSUE THREAD

**Issue by Bunnyfield** [in2code-de/femanager#507]
When running client side validation for a user registration used on a multidomain site with different user storage folders, the validation "uniqueInPage" fails, because the plugin setting is ignored and the default storagePid configured in `plugin.tx_femanager.persistence.storagePid` is used instead.

While there is a workaround by defining the same default storagePid as given by the plugin for each different plugin on the site, the default should actually be used as a fallback only if there is no ID given by the plugin at all.

**Comment by sbusemann** [comment]
First ifnding, it fails also, if the Frontend Validation is used in a site, which is a "subite":

the JS function getBaseURL works only for a "domain"

**Comment by sbusemann** [comment]
In the Flexform there is no option "pidStorage" available (anymore). Setting the Storage PID via TS works
My very minimal example for a second site within the same installation:

Constants:
plugin.tx_femanager.persistence.storagePid = 143
plugin.tx_femanager.settings.jQuery = 1

# Default PAGE object:
page = PAGE
page.10 < styles.content.get
module.tx_femanager.settings.configPID = 142
plugin.tx_femanager.settings.new.validation.username.uniqueInPage = 1
