### ISSUE TITLE
"&cHash comparison failed" in confirmation link after select new users to usergroup

### ISSUE THREAD

**Issue by jkbrands** [in2code-de/femanager#51]
Getting this error when I add new users to a frontend user group (Select Usergroups for new Users) while it works when Usergroup is blank.

**Comment by einpraegsam** [comment]
Pls give us some more information. What's your femanager and TYPO3 version? Do you use any extension for url-manipulation like realurl? If so, what's your configuration that influences femanager? What do you mean with `select usergroups`? Do you select a Usergroup in FlexForm or the user itself in frontend registration? What's your TypoScript configuration of femanager?

**Comment by Xarno** [comment]
I have that too and can give the information.

Typo3: 8.7.11
FEManager: 4.1.1

No real url or compareable Extension.

Stock Installation of FEManager, no extra Typoscript for FEManager. Only Typoscript for our Extension of FEManager. 
Registration Plugin has one autojoin group and „user must confirm“ setting.


Registered a User. Registration was successful. User Confirm Mail was send. Booth links are broken. 
Is it correct that booth links have „confirmCreateRequest“ as action?

Confirm Link:
https://digility.aws.koelnmesse.de/index.php?id=192&tx_femanager_pi1%5Buser%5D=25&tx_femanager_pi1%5Bhash%5D=f5634056b4c60739&tx_femanager_pi1%5Bstatus%5D=userConfirmation&tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New&cHash=cdf93748436e8decbc58d88485c866a8

Refuse Link: 
https://digility.aws.koelnmesse.de/index.php?id=192&tx_femanager_pi1%5Buser%5D=25&tx_femanager_pi1%5Bhash%5D=f5634056b4c60739&tx_femanager_pi1%5Bstatus%5D=userConfirmationRefused&tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New&cHash=5dbe57d44d0493b8f28878ba5b938ba6

**Comment by Xarno** [comment]
Bonuspoint while removing the cHash Parameter: The confirm process concludes even if Typo3 throws this error. The user is confirmed, activated, and it is an current frontenduser available for templates and such. But the rendering breaks with „Oops, and Error occured!“

**Comment by Xarno** [comment]
I tried different things, all without success.
* Disabling cHash generation for the tx_femanager_* parameter
* Disabling caching for the page
* Disabling double opt in
* Set redirect to profile page on successful login and failed login
* Set redirect with typoscript (maybe wrongly)

**Comment by Xarno** [comment]
Partial Suceess:
 * Setting Redirect Pids for redirect and userConfirmationRedirect in the Page Typoscript
https://github.com/in2code-de/femanager/blob/develop/Configuration/TypoScript/Main/setup.txt#L46
 * And having cHash disabled for the tx_femanager_* parameter
 * And have user needs to validate on

**Comment by webloft** [comment]
cHash error mostly thrown if the page was inaccessible (try set [FE][pageNotFound_handling] = 1 in setup)

Had the same error trying to hide the registration formular page after login by setting [Hide at login].

**Comment by sbusemann** [comment]
This ticket will be closed, as we don't support the 4.x branch anymore.
