### ISSUE TITLE
 TypeError  str_replace(): Argument #3 ($subject) must be of type array|string, null given

### ISSUE THREAD

**Issue by ToGetATockenOnly** [in2code-de/femanager#515]
TYPO3v11 with EXT:femanager v7.1.1 and current Firefox:
Open Plugin Content-Element in Backend. Hit F5. 

Class UserFieldOptions called by itemProcFunc() within plugin-Flexforms depends on a id=<pid> within a referer url, which is not always given. Examples - direct reload of backend page; reload after login timeout

It tries to read additional TSConfig values for the page. Implementation seems to be a bit weak. PID may come from the record itself. But prio to fix it should be low.

**Comment by ToGetATockenOnly** [comment]
To reproduce: TYPO3v11 list module in backend -> femanager plugin -> controller action "New->new" -> click "info" button in list view.

**Comment by sbusemann** [comment]
in V8 -> TYPO3 12 in can reproduce it
