### ISSUE TITLE
Class "In2code\Femanager\Utility\ObjectAccess" not found

### ISSUE THREAD

**Issue by t3webman** [in2code-de/femanager#516]
in 7.1.1 there where lines introduced in Classes/Utility/UserUtility.php that reffer to the class "ObjectAccess" which I cannot find ...
I tried to edit some user fields in the front-end which results in the error message in the title ...

Class "In2code\Femanager\Utility\ObjectAccess" not found

TYPO3 V11.5.28

**Comment by msollmann** [comment]
The TYPO3\CMS\Extbase\Reflection\ObjectAccess; is missing...

**Comment by mediaessenz** [comment]
I can confirm this problem

**Comment by t3webman** [comment]
> The use statement for ObjectStorage is also missing: `use TYPO3\CMS\Extbase\Persistence\ObjectStorage;`

what error does that cause ? I applied what msollmann suggested and I have no further errors reported ...

**Comment by mediaessenz** [comment]
It depends on your extended object. If it contains a property which using an object storage you get an error.

**Comment by dhoffmann1979** [comment]
Closed by #513
