### ISSUE TITLE
Issues with plaintext emails because of missing/wrong(?) configuration

### ISSUE THREAD

**Issue by proseriox** [in2code-de/femanager#519]
Hey folks,

I have encountered link issues when reading the html email as plaintext email.

Currently we are using the femanager `v7.1.1`  combined with TYPO3 `v11.5.29` . When we register on our website, a confirmation email will be sent to the user. We use this template for the confirmation email: `.../Templates/Email/CreateUserConfirmation.html` - The HTML view looks fine and it also works correctly. See:

![01](https://github.com/in2code-de/femanager/assets/16084295/e8c59076-aa18-4c5f-a0db-6e0931caef98)

The html email links look like this:

Confirm Profile (Confirm Profile)

```
https://[DOMAIN]/register?tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New&tx_femanager_pi1%5Bhash%5D=1d1372e9dc6257bb&tx_femanager_pi1%5Bstatus%5D=userConfirmation&tx_femanager_pi1%5Buser%5D=42462&cHash=[VALID-CHASH]
```

Delete profile (Delete profile)

```
https://[DOMAIN]/register?tx_femanager_pi1%5Baction%5D=confirmCreateRequest&tx_femanager_pi1%5Bcontroller%5D=New&tx_femanager_pi1%5Bhash%5D=1d1372e9dc6257bb&tx_femanager_pi1%5Bstatus%5D=userConfirmationRefused&tx_femanager_pi1%5Buser%5D=42462&cHash=[VALID-CHASH]
```

These links are valid and work perfectly.

However, if I change the email to a plain text email (Webmail Mittwald allows this - see the button ![image](https://github.com/in2code-de/femanager/assets/16084295/ea0e46cc-61c5-46e2-b4a7-396808b82a06) in the HTML mail), then the links are no longer valid. 

![image](https://github.com/in2code-de/femanager/assets/16084295/c635f0a2-7953-436d-96f4-b9285524a0b4)

Let's look at the links of the plain text email:

Confirm Profile (Confirm Profile)

```
https://[DOMAIN]/register?tx_femanager_pi1%5Baction%5D=confirmCreateRequest&amp;tx_femanager_pi1%5Bcontroller%5D=New&amp;tx_femanager_pi1%5Bhash%5D=1d1372e9dc6257bb&amp;tx_femanager_pi1%5Bstatus%5D=userConfirmation&amp;tx_femanager_pi1%5Buser%5D=42462&amp;cHash=[VALID-CHASH]
```

Delete profile (Delete profile)

```
https://[DOMAIN]/register?tx_femanager_pi1%5Baction%5D=confirmCreateRequest&amp;tx_femanager_pi1%5Bcontroller%5D=New&amp;tx_femanager_pi1%5Bhash%5D=1d1372e9dc6257bb&amp;tx_femanager_pi1%5Bstatus%5D=userConfirmationRefused&amp;tx_femanager_pi1%5Buser%5D=42462&amp;cHash=[VALID-CHASH]
```

Apparently, `&` becomes `&amp;` and this causes:

![image](https://github.com/in2code-de/femanager/assets/16084295/18a3d004-f99a-4eea-818b-b14a38ace465)

Even in DDEV the plain text email looks weird:

![image](https://github.com/in2code-de/femanager/assets/16084295/d67d2fc9-dbd3-4725-a552-8f6720855468)

In the line https://github.com/in2code-de/femanager/blob/develop/Classes/Domain/Service/SendMailService.php#L276 the `.html` file is read out but for plain text emails we should use `.txt` files. Should not we? This is how the core `felogin:ext` (forgot password) function works, I guess. 

**felogin - forgot pw - Test mail**

HTML:

![image](https://github.com/in2code-de/femanager/assets/16084295/6559fd7e-abf4-47ed-a0df-9ccefb938667)

Plain Text:

![image](https://github.com/in2code-de/femanager/assets/16084295/52bcfcd7-f727-4be6-b5f6-3c62fd8b2045)

In both cases the link is valid and the plaintext emails get the `.txt` file extension.

Am I missing something? Can you guys please take a look at this? It probably affects all emails.

**Comment by pixeldesu** [comment]
Technically speaking there is no configuration issue here. 

At the current time Femanager doesn't send out plain emails (https://github.com/in2code-de/femanager/blob/main/Classes/Domain/Service/SendMailService.php#L168-L171, there's no `->text()` call here), and it looks like Mittwald's Webmail is taking what's available (the HTML in this case) and displays it as plain as possible.

Looks like the HTML to plaintext transform is a bit too aggressive and it also includes HTML entities for the anchor href attribute.

I created a follow up issue for this #603.
