### ISSUE TITLE
'0' Number not pass `required` option.

### ISSUE THREAD

**Issue by akhamuliak** [in2code-de/femanager#52]
For example if I want to make gender or some other field field as select box and have `0` value for male and `1` for female.

Because of bug I can't set gender field as required, because `male` selection doesn't pass `required` validation.

https://github.com/in2code-de/femanager/blob/develop/Classes/Domain/Validator/AbstractValidator.php#L58
It's because `empty($var)` function return `false` if `$var = 0` or `$var = '0'`

So I think something like this will solve the issue

```
protected function validateRequired($value)
    {
        if (!is_object($value)) {
            if (is_numeric($value)) {
                return true;
            }
            return !empty($value);

        } elseif (count($value)) {
            return true;
        }
        return false;
    }
```

**Comment by sbusemann** [comment]
this will be in the next release.
