### ISSUE TITLE
Missing user notification after profil confirmation through admin

### ISSUE THREAD

**Issue by tw-wolfgang** [in2code-de/femanager#524]
Hi guys,

this is rather a missing feature than a bug:
In our setup every new profil must be confirmed by an admin first. This works just fine. The problem is, that the user doesn´t get to know if his profil request was confirmed, as there is no e-mail for this case. (only if his request gets deleted). The only chance is to inform him manually by the credentials given in his request. Would be nice if there was an option to inform him via e-mail (by default) as soon as his request was confirmed.

Might also be i´m missing something here, but i found nothing helpful in the documentation.

We are running fe manager in a TYPO3 11 environment

**Comment by tw-wolfgang** [comment]
Just kindly wanted to ask if you consider this feature usefull and if there is a chance it might be part of a future update.

**Comment by Patta** [comment]
This is already part of the extension. TypoScript "createUserNotify" https://github.com/in2code-de/femanager/blob/1c3df170182faa9ba970d79dcb4493d94be64665/Configuration/TypoScript/Main/setup.typoscript#L338
https://docs.typo3.org/p/in2code/femanager/7.2/en-us/Installation/Index.html#setup

**Comment by tw-wolfgang** [comment]
Thank you, sorry i must have missed this.
