### ISSUE TITLE
Issue on reload in InvitationController editAction due to 'userAlreadyConfirmed' status.

### ISSUE THREAD

**Issue by H-OsamaSultan** [in2code-de/femanager#527]
On reload in invitation editAction user gets redirected to statusAction with message "userAlreadyConfirmed" even we are not providing any data in form fields. We went through this issue it's because of this condition that is added in last version 

<img width="1329" alt="Screenshot at Sep 25 12-42-52" src="https://github.com/in2code-de/femanager/assets/100200268/0926b571-dbec-4620-9535-a117a858c87a">

it's because only the first time this condition work fine and we reload this page again as  $user->setDisable(false); in first attempt mark the disable to false and on redirect the condition of which i added the screenshort of gets true and it redirects to statusAction with the message "userAlreadyConfirmed".
![image](https://github.com/in2code-de/femanager/assets/100200268/20460ed5-0421-4aa7-ab22-adf196e3290f)

and because of this validation applied in setup.typoscript for validationEdit not working

How to reproduce this issue:

1) use invitation plugin, invite a user
2)click on confirm profile 
3)click on set password without providing any data or just reload this page

**Comment by pixeldesu** [comment]
I tested reloading the edit action after confirming my account and I'm still on the edit form. The message in this case is correct if we start from the confirm action at the point of reload, the user has already been confirmed after clicking the link.

<img width="471" alt="Screenshot 2024-11-05 at 15 25 34" src="https://github.com/user-attachments/assets/8699af34-fb7a-4cd7-a6ac-5cc229e3193f">

I'm not exactly sure how frequent the case of "reloading the edit form" really is, and for the message that's correct this is not really a bug/broken behaviour.
