### ISSUE TITLE
Usage of TYPO3 v12 Password Policy

### ISSUE THREAD

**Issue by rfuehricht** [in2code-de/femanager#528]
Hi!

I am currently on the Early Access Version compatible with TYPO3 v12.
I have activated the new Password Policies Feature of TYPO3, but it seems that EXT:femanager doesn't use this feature.

A user can be created with any password.

Am I missing something?

Regards,
Reinhard

**Comment by sbusemann** [comment]
You can define password settings via typoScript in the validation area.

**Comment by NatalieKH** [comment]
With the setting options for the password using TYPOscritp, I can only make the following settings:
mustInclude = number,letter,special
However, the TYPO3 v12 Password Policy also requires one letter in upper case and one in lower case. However, I cannot achieve this with the above setting. Or are there other parameters?
