### ISSUE TITLE
No verification under version 6.3.6

### ISSUE THREAD

**Issue by spiderrider** [in2code-de/femanager#533]
I updated on version 6.3.6 on Typo3 10.4.37 and the verification isn't possible anymore. I get the error message:
"Oops, an error occurred! Code: 20231231213507905bbb97"
Although the new user is in the database but no e-mail goes to the user and admin. What can I do?

Thanks
Harald

**Comment by sbusemann** [comment]
Please set config.contentObjectExceptionHandler = ß in your typoscript, to receive a speaking error message.

**Comment by spiderrider** [comment]
Thank you, now it works. I had to adjust my smtp mail handling settings.
