### ISSUE TITLE
In2code\Femanager\Domain\Validator\ServersideValidator::getValue(): Return value must be of type string|bool, int returned

### ISSUE THREAD

**Issue by pfuju** [in2code-de/femanager#539]
Hello 
there seems to be a bug in the ServersideValidator::getValue(), which requires a return value of type string or bool.
In case of additional fields should be validated like gender (int), etc. this funtions throws an exception.
Type decleration should be removed!

**Comment by mhuber84** [comment]
I can confirm this error

**Comment by tmhf** [comment]
I also can confirm this error (TYPO3 12.4.9, femanager 8.0.1)

**Comment by hannesbochmann** [comment]
I can confirm this error, too.

**Comment by hannesbochmann** [comment]
For everybody needing a fast fix, this patch will do it. But it's for sure no good fix.
[femanager.issue-539.txt](https://github.com/in2code-de/femanager/files/14479364/femanager.issue-539.txt)

**Comment by giesenmartin** [comment]
I can also confirm this issue. An Integer should be added to the return values of the getValue method. If the property is an Object or an ObjectStorage, an Integer value should be returned.

**Comment by pixeldesu** [comment]
This has been fixed in https://github.com/in2code-de/femanager/releases/tag/8.1.0
