### ISSUE TITLE
Image upload doesn't work with new field

### ISSUE THREAD

**Issue by p380** [in2code-de/femanager#543]
I want to have an additional image field in the form. In the form I extended a new custom field for the image.
Uploading an image works in an additional field, as well as in the default image field (image). 
 
 But when I remove the image from the 'image' field and want to add a new image I get an error.
 
 In2code\Femanager\DataProcessor\ImageManipulation::getNewImageName(): Argument #1 ($fileItem) must be of type array, string given
 
 Probably because the image is added in the custom field?
 If I remove this image from the custom field, then uploading the image to the default 'image' field works.
 
 Regards

**Comment by sbusemann** [comment]
The upload functionality will be reworked in v13 - so far I will close this issue
