### ISSUE TITLE
Classes/Domain/Validator/PasswordValidator.php throws an warning when in debug mode but not in live mode

### ISSUE THREAD

**Issue by grischpel** [in2code-de/femanager#544]
Classes/Domain/Validator/PasswordValidator.php throws an error when in debug mode but not in live mode

PHP Warning: Trying to access array offset on value of type null in /public/typo3conf/ext/femanager/Classes/Domain/Validator/PasswordValidator.php line 138

![image](https://github.com/in2code-de/femanager/assets/35844133/22e98b74-b2b1-4dec-a320-ce51ea9cb2a1)

```
 /**
     * Initialize Validator Function
     */
    protected function init()
    {
        $this->configuration = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS,
            'Femanager',
            'Pi1'
        );
        $this->cObj = $this->configurationManager->getContentObject();
        $this->piVars = GeneralUtility::_GP('tx_femanager_pi1');
        $this->actionName = $this->piVars['__referrer']['@action'];
    }

```

I called this from my own validator: 

```
public function validatePassword(User $user, string $password): bool {
	  $user->setPassword($password);

	  /** @var PasswordValidator */
	  $validator = GeneralUtility::makeInstance(\In2code\Femanager\Domain\Validator\PasswordValidator::class);
	  $validator->configurationManager = GeneralUtility::makeInstance(ConfigurationManager::class);

	  return $validator->isValid($user);
	}

```

I think the problem is, that my extension gives another name then this: ` $this->piVars = GeneralUtility::_GP('tx_femanager_pi1');`
in the header: 
```
tx_name_profile[__referrer][@controller]: User
tx_name_profile[__referrer][@action]: showProfile
tx_name_profile[__referrer][@extension]: Name
```

**Comment by pixeldesu** [comment]
I checked this and I don't our validators support use cases outside of `tx_femanager_` plugins, especially with the switch to v8 and multiple plugins, we now specifically check for things running in one of the allowed plugins through `PluginService`, so upgrading wouldn't fix this issue either.

Please reimplement the password checking logic in your case here.
