### ISSUE TITLE
auto login with TYPO3 12

### ISSUE THREAD

**Issue by weisgerberm** [in2code-de/femanager#548]
I have set up everything, but the automatic login does not work. (with and without confirmation)
Now I see in the .FemanagerFeaturesList.md file that "One step registration with autologin" is not working yet. Is this information from 9 months ago still up to date or have I configured something incorrectly?

I set this plugin.tx_femanager.settings.new.login = 1

**Comment by weisgerberm** [comment]
Any updates?

**Comment by zobnov** [comment]
+1 to the question. I'm looking for a solution, and I'm ready to contribute with coding. Thanks.

**Comment by sbusemann** [comment]
There is no easy solution at the moment. As far as i know, we need to implement a new event during the login process. Any help is welcome

**Comment by weisgerberm** [comment]
The problem is that you can't redirect and AutoLogin at the same time. I have removed the redirect block in my project because I don't need it. Now it works again.

https://github.com/weisgerberm/femanager/commit/d43c6fe6f0fb359cd7fa25a1be28fd0ffa67a503

**Comment by zobnov** [comment]
@weisgerberm Thank you, but it didn't help me, unfortunately. Do you happen to know more by now?

@sbusemann, could you point me to more details? I'd be willing to contribute my coding to resolve the issue. Thank you!
