### ISSUE TITLE
FE Image Upload does not work anymore since latest Typo3 12 Minor Update

### ISSUE THREAD

**Issue by gpazout** [in2code-de/femanager#555]
Since updating from Typo3 12.4.10 to 12.4.12 the image upload (or file upload generally speaking) via the FE does not work anymore!

I get the following Exception:
`
#1297759968 TYPO3\CMS\Extbase\Property\Exception
Exception while property mapping at property path "image.0": Property "name" was not found in target object of type "TYPO3\CMS\Extbase\Domain\Model\FileReference".
`

I am very confident, that the reason for that is the following patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81594
More particular the changes in `typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php`: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81594/6/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php

When I change `if ($useArgumentsWithoutNamespace && count($fileParameters))` back to `if (count($fileParameters))` the file upload works without any flaws!

Is anyone else experiencing the same issue? If so how did you fix it?

Are we supposed to use TypoConverters again for FE image upload? It is so weird, because as far as I understand the patch was originally unofficially introduced a few month ago as a fix, because apparently the Typo3 devs messed up and broke the FE image upload via TypoConverters back then.

**Comment by proseriox** [comment]
having the same issue in `v12.4`. 

In `v13` seems like the codeblock `...backwards compatibility...`  has been also removed. It works in `v13` fine.

v12 https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php
v13 https://github.com/TYPO3/typo3/blob/13.0/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php

hit me also up if someone knows how to fix it

**Comment by manuelportela** [comment]
@proseriox do you know what Andreas means by "Therefore, I personally would not fix it anymore to prevent breaking instances with a patchlevel release."?
Will it be re-fixed in 12? How do you go forward from here?

**Comment by gpazout** [comment]
> hit me also up if someone knows how to fix it

You need to adjust some code.

### Partial Image.html
from this:
```html
<f:form.upload
	id="femanager_field_image"
	property="image.0"
	class="custom-file-input" />
```
```html
<f:form.upload
	id="femanager_field_image"
	name="image"
	class="custom-file-input" />
```

### Controller
```php
protected function processUploadedImage($user)
{
        $uploadedFiles = $this->request->getUploadedFiles(); // the image is now in $uploadedFiles['image'], not in $uploadedFiles['user']['image']

        // ...allowed file types

        if (
            count($uploadedFiles) > 0
            && !empty($uploadedFiles['image'])
        ) {         
            $images = [];
            $images[] = $uploadedFiles['image']; // add image to an array (this way the original code in the foreach loop below does not have to be changed at all)

            foreach ($images as $uploadedFile) {
                      // rest of code unchanged
            }
}
```

**Comment by agentivcreatur** [comment]
> > hit me also up if someone knows how to fix it
> 
> You need to adjust some code.
> 
> ### Partial Image.html
> from this:
> 
> ```
> <f:form.upload
> 	id="femanager_field_image"
> 	property="image.0"
> 	class="custom-file-input" />
> ```
> 
> to this:
> 
> ```
> <f:form.upload
> 	id="femanager_field_image"
> 	name="image"
> 	class="custom-file-input" />
> ```
> 
> ### Controller
> ```
> protected function processUploadedImage($user)
> {
>         $uploadedFiles = $this->request->getUploadedFiles(); // the image is now in $uploadedFiles['image'], not in $uploadedFiles['user']['image']
> 
>         // ...allowed file types
> 
>         if (
>             count($uploadedFiles) > 0
>             && !empty($uploadedFiles['image'])
>         ) {         
>             $images = [];
>             $images[] = $uploadedFiles['image']; // add image to an array (this way the original code in the foreach loop below does not have to be changed at all)
> 
>             foreach ($images as $uploadedFile) {
>                       // rest of code unchanged
>             }
> }
> ```

I cannot confirm this solution. I changed the code as described and now I get the following error:

"Exception while property mapping at property path "image.name": The identity property "5-mb-example-file.pdf" is no UID."
![image](https://github.com/in2code-de/femanager/assets/91177237/8df55cef-cda4-4e1e-ace1-991c5f951449)

The error occurs before the "processUploadedImage" function.

Tested with 
TYPO3: 12.4.16
femanager: 8.1.0

**Comment by danieljanek78** [comment]
Same error here, tested with:
TYPO3 12.4.16
femanager 8.1.0

**Comment by karinakern** [comment]
> > hit me also up if someone knows how to fix it
> 
> You need to adjust some code.
> ### Partial Image.html
> 
> from this:
> 
> ```
> <f:form.upload
> 	id="femanager_field_image"
> 	property="image.0"
> 	class="custom-file-input" />
> ```
> 
> to this:
> 
> ```
> <f:form.upload
> 	id="femanager_field_image"
> 	name="image"
> 	class="custom-file-input" />
> ```
> 
> ### Controller
> 
> ```
> protected function processUploadedImage($user)
> {
>         $uploadedFiles = $this->request->getUploadedFiles(); // the image is now in $uploadedFiles['image'], not in $uploadedFiles['user']['image']
> 
>         // ...allowed file types
> 
>         if (
>             count($uploadedFiles) > 0
>             && !empty($uploadedFiles['image'])
>         ) {         
>             $images = [];
>             $images[] = $uploadedFiles['image']; // add image to an array (this way the original code in the foreach loop below does not have to be changed at all)
> 
>             foreach ($images as $uploadedFile) {
>                       // rest of code unchanged
>             }
> }
> ```

This works for me with TYPO3 12.4.16 and femanager 8.1.0, but ONLY on update, not on create.

Also, I get the following error when trying to delete the image in the edit form: "You are not allowed to delete this image"

![TYPO3_Exception](https://github.com/in2code-de/femanager/assets/7398582/f091ed8c-262b-4fc4-aa48-4ce9b8cf360d)

**Comment by danieljanek78** [comment]
Is there currently a solution to this problem?

**Comment by peterschoene** [comment]
I have same problem here.
Any help would be appreciated

**Comment by PascoeBergmann** [comment]
Same error here, tested with:
TYPO3 12.4.19
femanager 8.1.0
PHP 8.3

**Comment by akoenig-clickstorm** [comment]
Got the fileUpload working. But its pretty complicated. I've used the UploadedFileReferenceConverter Class from EXT:form https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/form/Classes/Mvc/Property/TypeConverter/UploadedFileReferenceConverter.php to create an FAL-Reference from an uploaded file for something else in my extension already.

This also influences the femanager image upload and after patching out the $this->request->getUploadedFiles(); call in 
processUploadedImage() fileupload for FE-User image is working again for me.
[femanager_disable_process_uploaded_image.patch.txt](https://github.com/user-attachments/files/17276134/femanager_disable_process_uploaded_image.patch.txt)
