### ISSUE TITLE
Confirmation link can be clicked multiple times

### ISSUE THREAD

**Issue by mhuber84** [in2code-de/femanager#559]
If the user clicks the link in the confirmation email multiple times, the finishers get executed every time. But they should get executed only once. 

A `return true;` in the `if ($user->getTxFemanagerConfirmedbyuser())` in NewController::statusUserConfirmation() helps. Can someony confirm this?

Edit: Removed "but then the userConfirmationRedirect is not executed anymore"

**Comment by epxfrho** [comment]
I can confirm that issue and the `return true;` workaround. Similar problem in `if ($user->getTxFemanagerConfirmedbyadmin())` in NewController::statusAdminConfirmation().

However, I do not find it necessary to redirect to the `newAction` at this point. The user clicks on the confirmation link several times, so he/she has an account, why show the form?

**Comment by akiessling** [comment]
Can confirm the issue, `return true;` works. The redirect should be dropped, i don't see the usecase for that either.

**Comment by mhuber84** [comment]
Are there any news on this issue?

**Comment by hannesbochmann** [comment]
I ran into this problem, too. A simple return true; is no enough. The redirect response object needs to be returned and used in the actual action.

**Comment by hannesbochmann** [comment]
The same problem exists for other actions as well. I provided a PR which fixes a redirects.
