### ISSUE TITLE
Issue overriding admin email settings

### ISSUE THREAD

**Issue by jonasarts** [in2code-de/femanager#56]
Upgraded to newest FEManager on newest Typo3 yesterday.
(Typo3 8.7.10 & FEManager V 4.1.1)

Added/Updated admin mail settings in Constants AND (for testing) Setup TypoScript, but they never get applied.

plugin.tx_femanager.settings.adminName = ...
plugin.tx_femanager.settings.adminEmail = ...

I always get sender Femager with mail femanager@domain.org.
Cleared all caches, even opcache.

Has anybody the same issue?

**Comment by netcoop** [comment]
No problem here. It takes the address from the plugin record, and if the TS for 
new.createAdminConfirmation.receiver is set than that overrides the plugin value. Works as advertised here, same versions as yours

**Comment by jonasarts** [comment]
Found it! In an extension template I overwrite

plugin.tx_femanager {
  view {
    templateRootPath = fileadmin/templates/femanager/Templates/
    partialRootPath = fileadmin/templates/femanager/Partials/
    layoutRootPath = fileadmin/templates/femanager/Layouts/
  }
}

Seems this removed the settings part (why ever): plugin.tx_femanager.settings...

As I moved the 'view' paths to the root template (where the settings reside) it started to work correctly.

Thanks for your quick answer @netcoop.
