### ISSUE TITLE
Resend User Confirmation Request in Backend View does not work

### ISSUE THREAD

**Issue by NiklasLazinbee** [in2code-de/femanager#564]
The Resend User Confirmation Request function in the backend sends an email but the links in the mail template are not created.
In addition, the wrong template is used, namely the original template and not the template in the customized path.

**Comment by sbusemann** [comment]
Please take care that the config is setup correctly:

Take care, that the setting "module.tx_femanager.settings.configPID" is set up for any site (see :ref:`Configuration in Confirmation Module <_confirmation-module>`)
