### ISSUE TITLE
Undeclared arguments passed to ViewHelper In2code\Femanager\ViewHelpers\Form\SelectViewHelper: defaultOption.

### ISSUE THREAD

**Issue by peterschoene** [in2code-de/femanager#579]
There is a change in ViewHelper ... defaultOption for form.select no longer exists.

![Bildschirmfoto 2024-05-29 um 08 59 40](https://github.com/in2code-de/femanager/assets/83782511/63f51b9b-cd42-48fa-bc6e-764d7fef6f13)

Migration: defaultOption to prependOptionLabel

```
<femanager:form.select
...
     prependOptionLabel="{f:translate(key:'pleaseChoose')}"
...
 />
```

**Comment by Patta** [comment]
https://github.com/in2code-de/femanager/commit/2cbdfd9d8cee9e209504b28281f716e6473853ae

**Comment by sbusemann** [comment]
I guess this is not a bug, but a task to update your own templates
