### ISSUE TITLE
What is better to choose for TYPO3 frontend user registration and management?

### ISSUE THREAD

**Issue by typo3ua** [in2code-de/femanager#58]
Hello!
I have:

- ext: sf_register
- ext: sr_feuser_register
- ext: femanager

But I stand is before choice... What is better to choose for TYPO3 frontend user registration and management?

**If is the ext: sf_register so why? What are its benefits?**

**Comment by einpraegsam** [comment]
You're asking in the github issues section of an extension which one the best extension is? Just test the extensions and see what fits to your needs.
