### ISSUE TITLE
TypoScript setting removeFromUserGroupSelection not working anymore in v8

### ISSUE THREAD

**Issue by Patta** [in2code-de/femanager#591]
TYPO3 12.4.22
PHP 8.2
femanager 8.2.0

The TypoScript setting `plugin.tx_femanager.settings.new.misc.removeFromUserGroupSelection = 23,42` is not working anymore in v8.2.0. All usergroups are inserted in the usergroup select field.

**Comment by zobnov** [comment]
+1 I have this issue as well.

**Comment by zobnov** [comment]
@Patta can you submit a pull request so this will get fixed for everyone, please? Everyone will be grateful to you, thanks!

**Comment by Patta** [comment]
@zobnov hard coding of the controller name to "new" in AbstractController would then only work as workaround for the usergroup field in the registration form. the getControllerName function in In2code\Femanager\Utility\FrontendUtility needs instead to be updated/migrated. 

https://github.com/in2code-de/femanager/blob/07228e30b9c18cfba5351d8f535333338216b3b2/Classes/Utility/FrontendUtility.php#L108
