### ISSUE TITLE
cannot read / manipuly fields from typoscript before saving

### ISSUE THREAD

**Issue by ja-sk** [in2code-de/femanager#61]
I want to let the user decide on their usergroup(s) as well as have them in one particular group as well. I thought using forceValues and building the usergroups from the user selection + my standard usergroup like this:

```
plugin.tx_femanager.edit.forceValues {
      beforeAnyConfirmation {
        usergroup = COA
        usergroup {
          10 = TEXT
          10.value = 1,
          20 = TEXT
          20.field = usergoup
        }
      }
    }
```

But I cannot access the field value here it seems. Is this on purpose?

TYPO3 8.7.10, femanager 4.1.1

edit: I also tried to approach this through edit.storeInDatabase.fe_users but was not successfull

**Comment by sbusemann** [comment]
You could use a hook and add your default usergroup in the hook
