### ISSUE TITLE
Validation broken in 2.6.1 :: AbstractValidator

### ISSUE THREAD

**Issue by GerdBezold** [in2code-de/femanager#63]
We had to alter the following code in the AbstractValidator to make all settings available:

femanager/Classes/Domain/Validator/AbstractValidator.php
protected function init()

from:
[...]
        $config = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK
        );
[...]

to
[...]
        $config = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK,
           'Femanager',
            'Pi1'
        );
[...]

An alternative would be to use the CONFIGURATION_TYPE_SETTINGS constant and then change the last line in the init() function:

from:
        $this->validationSettings = $config['settings'][$controllerName][$validationName];
to:
        $this->validationSettings = $config[$controllerName][$validationName];

I think the latter solution is already included in the current develop branch.

**Comment by sbusemann** [comment]
For version 2.6 we won't do any update anymore
