### ISSUE TITLE
No notification to user after admin confirms registration

### ISSUE THREAD

**Issue by HorstBaumann** [in2code-de/femanager#64]
TYPO3 8.7.10
femanager 4.1.1

the confirmation-mail (double-opt-in) is sent to the user,
and also the mail to the admin.
But after the admin confirms the registration of the user, there is no email to the user to let him know that his confirmation is accepted and noch active.

**Comment by HorstBaumann** [comment]
Found it:
plugin.tx_femanager.view.settings.new.email.createUserNotify._enable.value = 1

the default is "0" :-(

**Comment by Hobokens** [comment]
Better try this:
plugin.tx_femanager.settings.new.email.createUserNotify._enable.value = 1
