### ISSUE TITLE
Autologin does not work

### ISSUE THREAD

**Issue by christophlehmann** [in2code-de/femanager#65]
femanager 4.1.1
typo3 8.7.9

I included the default TypoScript with no further adjustments. After confirming the link in the mail the user is activated and \In2code\Femanager\Controller\AbstractController::loginPreflight is executed fully.

Problem is the missing "Set-Cookie" header, which is not done via \TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication::createUserSession()

and should be done before according to its description...

Calling
```
        if (!$tsfe->fe_user->isCookieSet()) {
            $tsfe->fe_user->start();
        }
```
before createUserSession() does not seem to work, hm..

**Comment by einpraegsam** [comment]
There is an experimental setting in extension manager settings available on login problems. Did you test this?

**Comment by christophlehmann** [comment]
No, but now and it works like a charm 👍It's exactly the solution where the fe cookie is not set before.

**Comment by einpraegsam** [comment]
thx
