### ISSUE TITLE
Email subject not translated when confirming in BE-module

### ISSUE THREAD

**Issue by netcoop** [in2code-de/femanager#67]
Strange issue:
When a new user registers using admin confirmation, all works well when the admin clicks the link in the email message to confirm the new account, but if the admin uses the BE-module to confirm it, the confirmation email has an untranslated subject ('Your registration was confirmed').

Strange thing is that the rest of the message is properly translated, so it maybe something with the TSFE environment not being fully initialized? The subject is a TS label (emailCreateUserNotifySubject) and does not get translated, while the Fluid template (message body) works fine.

**Comment by sbusemann** [comment]
@netcoop can try it again, i changed the way the TS is taken in BE. Please reopen the issue, if it still does not work.

**Comment by netcoop** [comment]
@sbusemann I just tested with latest develop branch (which is the same as develop branch currently), and the issue still exists.

**Comment by sbusemann** [comment]
@netcoop I will take a look, the next time i prepare a bugfix release

**Comment by sbusemann** [comment]
The Email process was reimplented in Version 6.0 - now a real FE request is send out.
