### ISSUE TITLE
`lettersOnly` Validation failes with umlauts

### ISSUE THREAD

**Issue by derhofbauer** [in2code-de/femanager#70]
Version 2.6.0
Typo 7.6.21

`plugin.tx_femanager.settings.new.validation.[field].lettersOnly = 1` does not successfully validate, when input contains German umlauts. Names like Günther Müller are not successfully validated, but get an error message like "only letters are allowed". Please consider to respect umlauts within `lettersOnly` serverside validation.

**Comment by sbusemann** [comment]
I will check this for the current version. For 2.6 we won't do a fix.
