### ISSUE TITLE
Image required not working

### ISSUE THREAD

**Issue by Gregor-Agnes** [in2code-de/femanager#73]
Hi and thx for the great femanager!

If I set image field as required, I get a message (serverside: Field Image is required) even if I uploaded an image.
If I unset required on image field and upload an image, everything works fine.

Any hints?

**Comment by marclindemann** [comment]
i think the Problem is that web/typo3conf/ext/femanager/Classes/Domain/Validator/ServersideValidator.php  getValue($user,"image") will return a null value because $current->getUid() is null at time of check
