### ISSUE TITLE
[Typo3 v8.7.12] Setting keepPasswordIfEmpty does not work

### ISSUE THREAD

**Issue by Xarno** [in2code-de/femanager#76]
If keepPasswordIfEmpty is set (which is the default) it does not work, if the Password field is added to the edit form. The extension code unsets it, but the typo3 db layer sees a modification and updates the password to <empty>.

Partial workaround: Set Password as required

**Comment by ingeniumdesign** [comment]
here the same, the keepPasswordIfEmpty dont works in femanager 4.2.2

**Comment by ingeniumdesign** [comment]
new infos?

**Comment by ingeniumdesign** [comment]
under 4.2.5 dont work :(

**Comment by ingeniumdesign** [comment]
push up! :(
after 1 year dont work :(

**Comment by djangones** [comment]
Possibly there is a relation, if the extension was extended by own fields during the registration with an own extension, as it is described in the manual.
I have two similar installations (Live/Staging) each with its own extension to extend the registration with its own fields. So far the option "keepPasswordIfEmpty" worked as expected but now I have adjusted the own extension in the staging environment so that the error messages/warnings in PHP7 are no longer triggered. I proceeded as described here: https://github.com/einpraegsam/femanagerextended/issues/1
So the warnings in PHP7 disappear, but the option "keepPasswordIfEmpty" does not work anymore and the password field is simply set to empty in the DB...
I hope this helps in reproducing and debugging the problem.

**Comment by cdominpxp** [comment]
Do you have added parent::initializeUpdateAction(); in your own initializeUpdateAction() to call the parent function?

**Comment by kimchristiansen** [comment]
I have an Issue with keepPasswordIfEmpty=1 only if JavaScript validation is active.

Femanager Edit plugin with all fileds (password included) and javascript validation turned off. I have no problem with editing fileds with empty password.
This is how i turned javascript validation off:
```
includeJSFooter {
    femanagerValidation = >
    femanager = >
}
```
If i have JavaScript validation turned on, i get an AJAX Request saying password is required.
any ideas?

TYPO3 9.5.11
PHP 7.214
Femanager 5.1.1
I did not extend the Femanager

**Comment by andyhausmann** [comment]
I can confirm that adding parent::initializeUpdateAction(); in your Class, which extends EditController, will fix this issue.

In my case, we implemented a PHP 7 Hotfix for an older project not only for wrong type hints but also an exception which happens to occur if you also extend the User Class.

```php
class UserEditController extends EditController
{
	public function initializeUpdateAction()
	{
		if ($this->arguments->hasArgument('user')) {
			/** @var \OwnVendor\OwnExtension\Xclass\Extbase\Mvc\Controller\Argument $user */
			$user = $this->arguments['user'];
			$user->setDataType(OwnUser::class);
		}
		parent::initializeUpdateAction();
	}

	public function updateAction(DefaultUser $user)
	{
		assert($user instanceof OwnUser);
		parent::updateAction($user);
	}
}
```

**Comment by Patta** [comment]
I can confirm, that keepPasswordIfEmpty is not working on edit form, even if password required is 0.

TYPO3 9.5.18
PHP 7.3.17
Composer mode
femanager 5.2.0

client validation enabled
custom feuser fields

**Comment by bh-teufels** [comment]
i tired the fix from andyhausmann but not working for me

```
class EditController extends \In2code\Femanager\Controller\EditController {
    //should fix not working keep password if empty error (https://github.com/in2code-de/femanager/issues/76)
    /**
     * @return void
     */
    public function initializeUpdateAction()
    {
        parent::initializeUpdateAction();
    }
}
```

**Comment by sbusemann** [comment]
I tested this issue with the current version of femanager:

* setup a page with the plugin (edit view) and do not set password or password repeat to required
* Login as a user
* go to the edit view
* change data (but do not change password)
* logout 
* Login again

works

I will close this issue therefor.
