### ISSUE TITLE
Custom Validators do not work as documented

### ISSUE THREAD

**Issue by p1ngb4ck** [in2code-de/femanager#77]
Hi !

I use TYPO3 8.7.13 and the custom-validator-setting does not work as documented. The TS-Setting 
tx_femanager.settings.edit.validation.password {
custom = value
}
does not result in validation-data containing "custom(value)" in the password-input in the form as it should. If you add required = 1, data-validation contains "required," (note the comma at the end!), if you remove custom = value, data-validation contains only "required".
Can anybody confirm this behaviour ?!

And btw. : if I do tx_femanager.settings.edit.validation.password = custom, I get a data-validation tag containing "0(custom)". This is a workaround I will test for now (using a validate0 - method inside the controller)
Any help would be greatly appreciated

**Comment by sbusemann** [comment]
is merged
