### ISSUE TITLE
resend doi mail - confirm profile link does not work

### ISSUE THREAD

**Issue by AMartinNo1** [in2code-de/femanager#80]
The mail sent to the user after requesting the doi mail again contains an invalid link. I receive following error:
```
The action "confirmCreateRequest" (controller "New") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.
```

To fix this one needs to adjust the FlexFormPI1.xml file.
```
typo3conf/ext/femanager/Configuration/FlexForms/FlexFormPi1.xml:47
```
To this line one needs to add `New->confirmCreateRequest;`

**Comment by sbusemann** [comment]
this is fixed in develop and will be released in the next version
