### ISSUE TITLE
Add configPID documentation

### ISSUE THREAD

**Issue by sbusemann** [in2code-de/femanager#85]
it can be found in femanager/Documentation/Installation/Index.rst

In order to supply all functions also in BE, a page is needed, where the whole frontend ts configuration can be loaded from.

So please set module.tx_femanager.settings.configPID = 1 at your root page of your installation (and replace 1 with the page where the femanger ts can be found)

**Comment by t3webman** [comment]
It is not very clear what is expected, I have a multisite for example, the smaller site needs a frontend user registration, so I included the plugin on the root page of this site (PID 14) ... setting module.tx_femanager.settings.configPID to this page (14) does not resolve the error message.

In a latter moment also the main site will have a frontend user administration, so I'd have two separate settings (only small details are peculiar to one site like usergroup) ...
