### ISSUE TITLE
Registration with autologin saves ses_data in "wrong format" and destroys existing ses_data

### ISSUE THREAD

**Issue by linnearad** [in2code-de/femanager#87]
Probably the same as #57 

I have a solution where you in the process for registration to events has to log in or register a user. To redirect to the correct page after registration the id of the event and some other values are stored as ses_data

![image](https://user-images.githubusercontent.com/5416959/41339235-9a347d5c-6ef4-11e8-9e88-cd9bacb2dcf4.png)

When you click on registration you get two options, either to log in or to create a new user.  With log in the session is transfered coorect to the logged in user.

But if i test with creating a new user the ses_data is changed to (binary/image). Which I suppose isn't correct. And it also destroys existing ses_data

![image](https://user-images.githubusercontent.com/5416959/41339787-0579427c-6ef6-11e8-8b95-cef05ea7b881.png)

Probably this is also the reason that autologin isn't working in all cases.

Forgot following: TYPO3 8.7.16, Femanager 4.2.2

**Comment by stillerfritz** [comment]
I can confirm this issue. 
Creating a new account with auto-login clears existing session data whereas login existing user with felogin does not.
Login itself is working. the setting "basic.setCookieOnLogin" does not influence this.

TYPO3 8.7.18
FeManager 4.2.2

**Comment by sbusemann** [comment]
duplicates #229
