### ISSUE TITLE
storeInDatabase fails

### ISSUE THREAD

**Issue by Hobokens** [in2code-de/femanager#89]
TYPO3 8.7.16, Femanager 4.2.2.
For testing purposes I have activated the 'storeInDatabase-Feature' in 'TypoScript/Main/Setup.text'. Unfortunately, no entries are created in the "tt_address" table. The same applies to the example in the FAQ https://docs.typo3.org/typo3cms/extensions/femanager/FAQ/Index.html?#q-how-can-i-store-values-in-another-table.
My goal is to fill the field'name' with the values of the fields'firstName' and'lastName' during the registration process, which I tried in vain this way:

```
plugin.tx_femanager {
	settings {
		new {
			storeInDatabase {
				fe_users {
					_enable = TEXT
					_enable.value = 0

					name = COA
					name {
						10 = TEXT
						10.field = firstName
						20 = TEXT
						20.field = lastName
					}
				}
			}
		}
	}
}
```

**Comment by sbusemann** [comment]
@Hobokens you are trying to store in the fe_users table, please user tt_adress

**Comment by Hobokens** [comment]
Hi @sbusemann,
thanks for your advice. My description of the issue is a lit bit confusing cause I mention tt_address first and then try to store the value in fe_users. Sorry for that. 
Here is what I want to say: it doesn't matter whether  I try to store the value in tt_taddress or in fe_users - the values are never stored.
BTW: My aim is to store the values in fe_users.

Thanks a lot for the great extension!

**Comment by sbusemann** [comment]
In Version 6.x this is fixed and all tests do work
