### ISSUE TITLE
Extending possible fields in registration form

### ISSUE THREAD

**Issue by logeecom** [in2code-de/femanager#90]
This is more of a question or feature request than a specific issue.
Currently user can select specific fields from `fe_users` table should be displayed on registration form. If I extend this table, my field will still not be available.

Is there a way to extend this with my extension so additional fields are available on registration form and on user profile (edit) form?

**Comment by Hobokens** [comment]
Did you see the example extension https://github.com/einpraegsam/femanagerextended ?

**Comment by logeecom** [comment]
Thanks for this! This is not as I expected to be so we will have to go different way. Thanks for your help.
