### ISSUE TITLE
Please, add the password validator: mustInclude = uppercase

### ISSUE THREAD

**Issue by alhimik1986** [in2code-de/femanager#91]
Hi!
In the user registration I can use the follow password validations:
plugin.tx_femanager.settings.validation.password.mustInclude = number,letter,special, space

But I need to add there another one validator, which can check the presence of large letters.
That validator can be named like "uppercase" or largeLetter.

It's not difficult. I can do it myself, but I can't update the module afterwards.

**Comment by sbusemann** [comment]
@alhimik1986 feel free to create a pull request

**Comment by sbusemann** [comment]
solved with https://github.com/in2code-de/femanager/pull/190
