### ISSUE TITLE
typo3 in documentation?

### ISSUE THREAD

**Issue by beyring** [in2code-de/femanager#92]
Hi,

in the documentation to extend the femanager with fields, the typoscript looks like this:

config.tx_extbase{
        persistence{
                classes{
                        In2\Femanager\Domain\Model\User {
                                subclasses {
...
...
...

I guess the namespace for the original model has to be In2Code\... instead of In2\....

Is that correct?

Link to docu:
https://docs.typo3.org/typo3cms/extensions/femanager/1.0.11/ExtfeManager/BestPractice/AddingNewFieldsToFeUsersWithYourOwnExtension/Index.html

Best from munich,
Ben

**Comment by sbusemann** [comment]
You are referring to an updated version of femanager (1.0.11). You find the current and correct documentation at https://github.com/in2code-de/femanager/blob/develop/Documentation/Features/NewFields/Index.rst

**Comment by beyring** [comment]
Thanks for the quick response!
