### ISSUE TITLE
Subject not translated on confirmation email

### ISSUE THREAD

**Issue by pagliaso** [in2code-de/femanager#97]
Hello,

At the moment I am unable to translate the subject of the email that is sent to the user when he/she request and account and is required the confirmation by email.

I have found references to issues/60468 on the forge, but can not find the page.

I have typo3 8.7.19, and I am using femanager 4.2.2

I can translate the rest of the labels correclty and can do  things as expected on this wonderful extension, but I have been blocked with this for the last few days.

I hope someone can help me a little bit, many thanks and kind regards from Spain,

Alberto

**Comment by danielkoch** [comment]
Should work, see also here: https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial/UsingGetText/Index.html

But looks like the `getText` functionality is not working anymore.

You can use:
´´´
subject.value = My string
´´´

**Comment by ducrot** [comment]
Use custom translations with [locallangXMLOverride](https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/Internationalization/ManagingTranslations.html?highlight=locallangxmloverride#custom-translations) instead _LOCAL_LANG.

myextension/ext_localconf.php:  
`
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:femanager/Resources/Private/Language/locallang.xlf'][] = 'EXT:myextension/Resources/Private/Language/Overrides/de.locallang.xlf';
`

myextension/Resources/Private/Language/Overrides/de.locallang.xlf:
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
	<file source-language="en" target-language="de" datatype="plaintext" original="messages" date="2019-26-28T11:45:16Z" product-name="myextension">
		<header/>
		<body>
            <trans-unit id="emailCreateUserConfirmationSubject" approved="yes">
                <source>Please confirm your profile creation request</source>
                <target state="translated">Bitte bestätige deine Registrierung</target>
            </trans-unit>
		</body>
	</file>
</xliff>
```

**Comment by JenHa** [comment]
This issue is a little older, but I got the same Problem. 
In general the mail subjects seem to be hard coded now. 
E.g. https://github.com/in2code-de/femanager/blob/develop/Classes/Controller/AbstractController.php#L517, 
https://github.com/in2code-de/femanager/blob/develop/Classes/Controller/AbstractController.php#L158 and 
https://github.com/in2code-de/femanager/blob/develop/Classes/Controller/AbstractController.php#L194

To change these labels I have to xclass the controller, which isn't very elegant. It would be great if the subjects could be added to the labels.

**Comment by Moongazer** [comment]
Why is nobody sponsoring 1 min work for this great extension since over 2 years?! :smiley_cat: 

https://github.com/in2code-de/femanager/pull/312

**Comment by martinschoene** [comment]
The issue is still open!
The subject originally reported from @pagliaso is the hardcoded subject in  the AbstractController.php in line 517.

greetings
martin
